import type { SeedRecipe } from './types.js';

/**
 * The house recipes: 55 dishes people can cook, save, shelve and adapt before (or instead of)
 * connecting an AI. Deliberately spread across cuisines, meal types, dietary needs and effort.
 */
export const HOUSE_RECIPES: SeedRecipe[] = [
  // ---------------------------------------------------------------- breakfast
  {
    emoji: '🍅',
    title: 'Shakshuka with feta and herbs',
    summary: 'Eggs poached in a spiced tomato and pepper sauce, finished with crumbled feta. One pan, twenty-five minutes, bread for dipping.',
    cuisine: 'Middle Eastern',
    meal: 'breakfast',
    serves: 2,
    total: 25,
    active: 15,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free'],
    tags: ['one-pan', 'brunch', 'eggs', 'spicy'],
    equipment: ['wide skillet with lid'],
    techniques: ['sautéing', 'poaching'],
    ing: ['2 tbsp olive oil', '1 onion, diced', '1 bell pepper, sliced', '3 cloves garlic, minced', '1 tsp cumin', '1 tsp paprika', '1/2 tsp chili flakes', '400 g canned tomatoes', 'salt', '4 eggs', '60 g feta', 'small bunch parsley, chopped', '?warm pita, for dipping'],
    steps: [
      ['Soften the vegetables', 'Warm the olive oil in a wide skillet over medium heat. Add the onion and bell pepper with a pinch of salt and cook until soft and starting to brown at the edges.', 480, 'Medium heat'],
      ['Bloom the spices', 'Stir in the garlic, cumin, paprika and chili flakes. Cook for a minute until fragrant, then pour in the tomatoes, crushing any whole ones with the spoon. Simmer until thickened slightly.', 420, null, 'The sauce should be thick enough to hold a well for each egg.'],
      ['Poach the eggs', 'Make four wells in the sauce and crack an egg into each. Season the eggs, cover, and cook until the whites are set but the yolks still jiggle.', 300, 'Low heat', 'Check at 4 minutes; residual heat keeps cooking them after you lift the lid.'],
      ['Finish', 'Crumble the feta over the top, scatter the parsley, and bring the pan to the table with warm pita.'],
    ],
    subs: [['feta', 'goat cheese or leave it out', 'still creamy and salty'], ['pita', 'gluten-free bread or rice']],
    storage: 'The sauce keeps for 3 days in the fridge; reheat and poach fresh eggs in it.',
    n: [340, 18, 18, 22],
    caption: 'The house shakshuka. Sunday brunch in one pan — bring bread.',
    daysAgo: 21,
  },
  {
    emoji: '🥣',
    title: 'Overnight oats with berries and chia',
    summary: 'Five minutes the night before, breakfast for the week. Creamy oats set with chia, topped with whatever fruit you have.',
    cuisine: 'American',
    meal: 'breakfast',
    serves: 1,
    total: 485,
    active: 5,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'gluten-free'],
    tags: ['make-ahead', 'no-cook', 'meal-prep', 'quick'],
    equipment: ['jar with lid'],
    techniques: ['soaking'],
    ing: ['50 g oats', '1 tbsp chia seeds', '150 ml oat milk', '1 tsp maple syrup', '1/2 tsp vanilla', 'pinch cinnamon', '1 handful berries', '?1 tbsp pumpkin seeds, toasted'],
    steps: [
      ['Mix', 'Stir the oats, chia seeds, oat milk, maple syrup, vanilla and cinnamon together in a jar. Make sure no chia is clumped at the bottom.'],
      ['Rest overnight', 'Lid on, into the fridge for at least 4 hours, ideally overnight. The chia thickens everything into a pudding.', 28800],
      ['Top and eat', 'Loosen with a splash more milk if it is too thick. Top with berries and a scatter of toasted pumpkin seeds.'],
    ],
    subs: [['oat milk', 'any milk you like'], ['maple syrup', 'honey (not vegan) or mashed banana']],
    makeAhead: 'Make five jars on Sunday; they keep all week.',
    storage: '4 days in the fridge, lidded.',
    n: [310, 9, 48, 9],
    caption: 'Meal-prep breakfast that actually tastes good on day four.',
    daysAgo: 20,
  },
  {
    emoji: '🌶️',
    title: 'Turkish menemen',
    summary: 'Soft scrambled eggs folded through slow-cooked peppers and tomatoes. The trick is patience: low heat, big curds, no rushing.',
    cuisine: 'Turkish',
    meal: 'breakfast',
    serves: 2,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['one-pan', 'eggs', 'brunch', 'quick'],
    equipment: ['nonstick skillet'],
    techniques: ['sweating', 'soft scrambling'],
    ing: ['2 tbsp olive oil', '1 tbsp butter', '2 green peppers, finely chopped', '3 tomatoes, diced', '1/2 tsp chili flakes', 'salt', '4 eggs', 'small bunch parsley, chopped', '?crusty bread'],
    steps: [
      ['Cook the peppers', 'Heat the oil and butter over medium-low. Add the peppers and cook gently until completely soft — this takes longer than you think.', 480, 'Medium-low heat'],
      ['Add tomatoes', 'Tip in the tomatoes, chili flakes and a good pinch of salt. Cook until the tomatoes break down into a loose, jammy sauce.', 360],
      ['Scramble slowly', 'Crack the eggs straight into the pan. Let them sit for 20 seconds, then fold gently with a spatula so you get large soft curds streaked with tomato. Pull the pan off the heat while they still look a little wet.', 150, 'Low heat', 'Menemen should be spoonable, not firm.'],
      ['Serve', 'Scatter parsley and eat from the pan with bread.'],
    ],
    subs: [['butter', 'more olive oil', 'makes it dairy-free']],
    n: [330, 16, 14, 24],
    caption: 'Menemen — the softest scrambled eggs you will make this year.',
    daysAgo: 19,
  },
  {
    emoji: '🍚',
    title: 'Ginger scallion congee',
    summary: 'Rice simmered until it collapses into silk, with ginger warmth and a pile of toppings. Comfort in a bowl, gentle on everything.',
    cuisine: 'Chinese',
    meal: 'breakfast',
    serves: 4,
    total: 75,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['comfort', 'big-batch', 'budget', 'soothing'],
    allergens: ['soy'],
    equipment: ['large pot'],
    techniques: ['simmering'],
    ing: ['200 g rice', '1.5 l stock', '1 thumb ginger, julienned', '2 cloves garlic, crushed', 'salt', '4 spring onions, sliced', '2 tbsp tamari', '1 tbsp sesame oil', '?chili oil', '?fried shallots'],
    steps: [
      ['Rinse and start', 'Rinse the rice until the water runs mostly clear. Put it in a large pot with the stock, ginger and garlic and bring to a boil.', null, 'High heat'],
      ['Simmer low and slow', 'Drop to a bare simmer, lid ajar, and stir every 10 minutes so nothing catches. It is done when the grains have burst and the whole thing is thick and creamy.', 3600, 'Low heat', 'Too thick? Add hot water. Too thin? Keep going.'],
      ['Season', 'Taste and salt generously — congee needs more than you expect.'],
      ['Top', 'Ladle into bowls. Finish each with spring onions, a drizzle of tamari and sesame oil, chili oil and fried shallots if you have them.'],
    ],
    subs: [['stock', 'water plus a little extra salt'], ['tamari', 'soy sauce', 'if gluten is fine']],
    makeAhead: 'Congee thickens as it sits; loosen with water when reheating.',
    storage: '4 days in the fridge.',
    n: [230, 6, 44, 4],
    caption: 'Congee for cold mornings. Toppings are the whole point.',
    daysAgo: 18,
  },
  {
    emoji: '🥞',
    title: 'Banana oat pancakes',
    summary: 'Blender pancakes with no flour and no added sugar — bananas, oats and eggs do the work. Fluffy, nutty, freezer-friendly.',
    cuisine: 'American',
    meal: 'breakfast',
    serves: 2,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['kid-friendly', 'blender', 'freezer-friendly'],
    equipment: ['blender', 'nonstick skillet'],
    techniques: ['blending', 'pan-frying'],
    ing: ['2 bananas', '2 eggs', '100 g oats', '1 tsp baking powder', '1/2 tsp cinnamon', 'pinch salt', '1 tsp vegetable oil', '?maple syrup', '?berries'],
    steps: [
      ['Blend the batter', 'Blend the bananas, eggs, oats, baking powder, cinnamon and salt until smooth. Let it sit for 5 minutes so the oats hydrate and the batter thickens.', 300],
      ['Cook', 'Heat a nonstick skillet over medium and brush with oil. Pour in small pancakes — about 3 tablespoons each. Cook until bubbles form and the edges look dry, then flip and cook another minute.', 180, 'Medium heat', 'Keep them small; the batter is delicate and small ones flip cleanly.'],
      ['Serve', 'Stack with berries and maple syrup.'],
    ],
    subs: [['eggs', '2 tbsp ground flax + 5 tbsp water', 'makes them vegan, a little denser']],
    storage: 'Freeze cooked pancakes in a single layer; toast to reheat.',
    n: [380, 14, 58, 10],
    caption: 'Three-ingredient-ish pancakes. The kids do not notice the oats.',
    daysAgo: 17,
  },
  {
    emoji: '🥑',
    title: 'Smoked salmon and avocado toast with pickled shallot',
    summary: 'Good bread, smashed avocado with lime, silky smoked salmon and a quick-pickled shallot that makes it taste like a café.',
    cuisine: 'Scandinavian',
    meal: 'breakfast',
    serves: 2,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['pescatarian', 'dairy-free', 'nut-free'],
    tags: ['quick', 'brunch', 'no-cook', 'high-protein'],
    equipment: ['toaster'],
    techniques: ['quick pickling'],
    ing: ['1 shallot, thinly sliced', '2 tbsp vinegar', 'pinch sugar', '1 avocado', '1/2 lime, juiced', 'salt', 'black pepper', '2 slices bread', '100 g smoked salmon', 'few sprigs dill', '?chili flakes'],
    steps: [
      ['Pickle the shallot', 'Toss the shallot with the vinegar, a pinch of sugar and a pinch of salt. Leave it while you do everything else — 10 minutes is enough to take the edge off.', 600],
      ['Smash the avocado', 'Mash the avocado roughly with the lime juice, salt and pepper. Keep some texture.'],
      ['Toast and build', 'Toast the bread until properly crisp. Spread thickly with avocado, drape over the salmon, and top with drained pickled shallot, dill and chili flakes.'],
    ],
    subs: [['smoked salmon', 'smoked trout or a fried egg'], ['bread', 'gluten-free bread or a rice cake']],
    n: [420, 20, 30, 24],
    caption: 'Café toast at home. The pickled shallot is non-negotiable.',
    daysAgo: 16,
  },
  {
    emoji: '🥬',
    title: 'Green smoothie bowl',
    summary: 'Thick enough to eat with a spoon: spinach, frozen mango and banana blended with oat milk, topped with crunch.',
    cuisine: 'Californian',
    meal: 'breakfast',
    serves: 1,
    total: 10,
    active: 10,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['no-cook', 'quick', 'fruit'],
    equipment: ['blender'],
    techniques: ['blending'],
    ing: ['1 handful spinach', '150 g mango, frozen', '1 banana, frozen', '100 ml oat milk', '1 tbsp chia seeds', 'Toppings: 1 tbsp pumpkin seeds', 'Toppings: 1 handful berries', 'Toppings: ?2 tbsp toasted coconut'],
    steps: [
      ['Blend thick', 'Blend the spinach, mango, banana, oat milk and chia until smooth. Use as little liquid as the blender allows so it stays spoonable.', null, null, 'Frozen fruit is what makes it thick; fresh fruit needs ice.'],
      ['Top', 'Pour into a bowl and arrange the pumpkin seeds, berries and coconut on top.'],
    ],
    n: [340, 8, 62, 8],
    caption: 'Spoonable smoothie. Frozen banana is the secret to the texture.',
    daysAgo: 15,
  },
  // ---------------------------------------------------------------- lunch
  {
    emoji: '🥗',
    title: 'Greek chickpea salad',
    summary: 'Cucumber, tomato, olives and chickpeas in a lemon-oregano dressing. Gets better after an hour in the fridge.',
    cuisine: 'Greek',
    meal: 'lunch',
    serves: 4,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['no-cook', 'meal-prep', 'summer', 'budget'],
    equipment: ['large bowl'],
    techniques: ['dressing'],
    ing: ['2 cans chickpeas, drained', '1 cucumber, diced', '250 g cherry tomatoes, halved', '1/2 red onion, thinly sliced', '80 g olives, halved', 'Dressing: 4 tbsp olive oil', 'Dressing: 1 lemon, juiced', 'Dressing: 1 tsp oregano', 'Dressing: 1 clove garlic, minced', 'salt', 'black pepper', '?100 g feta, crumbled'],
    steps: [
      ['Make the dressing', 'Whisk the olive oil, lemon juice, oregano, garlic, salt and pepper in the bottom of a large bowl.'],
      ['Toss', 'Add the chickpeas, cucumber, tomatoes, red onion and olives. Toss well and taste — it will want more salt than you think.'],
      ['Rest', 'Leave for 30 minutes if you can; the onion softens and the chickpeas soak up the dressing. Top with feta if using.', 1800],
    ],
    subs: [['chickpeas', 'white beans'], ['feta', 'leave it out for vegan']],
    makeAhead: 'Keeps 3 days dressed; add feta just before serving.',
    n: [320, 12, 34, 16],
    caption: 'The lunch that survives a Monday-to-Wednesday in the fridge.',
    daysAgo: 14,
  },
  {
    emoji: '🍜',
    title: 'Turkish red lentil soup (mercimek çorbası)',
    summary: 'Red lentils, carrot and potato cooked down and blended smooth, finished with lemon and paprika butter. Cheap, filling, freezer gold.',
    cuisine: 'Turkish',
    meal: 'lunch',
    serves: 6,
    total: 40,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['soup', 'big-batch', 'budget', 'freezer-friendly'],
    equipment: ['large pot', 'blender or stick blender'],
    techniques: ['simmering', 'blending'],
    ing: ['2 tbsp olive oil', '1 onion, diced', '1 carrot, diced', '1 potato, diced', '2 cloves garlic, minced', '1 tbsp tomato paste', '1 tsp cumin', '1 tsp paprika', '300 g lentils, red', '1.5 l stock', 'salt', '1 lemon, cut into wedges', '?1 tsp chili flakes', '?2 tbsp olive oil, for the paprika drizzle'],
    steps: [
      ['Sweat the vegetables', 'Warm the oil in a large pot. Cook the onion, carrot and potato with a pinch of salt until softened.', 420, 'Medium heat'],
      ['Spice and simmer', 'Stir in the garlic, tomato paste, cumin and paprika for a minute. Add the lentils and stock, bring to a boil, then simmer until the lentils have completely collapsed.', 1200, 'Low heat', 'Skim any foam in the first few minutes.'],
      ['Blend', 'Blend until smooth. Season well with salt. Thin with water if needed — it should pour, not plop.'],
      ['Finish', 'Warm the extra olive oil with chili flakes and a pinch of paprika for 30 seconds and drizzle over each bowl. Serve with lemon wedges to squeeze over.', 30],
    ],
    subs: [['stock', 'water and a stock cube']],
    storage: 'Freezes perfectly for 3 months.',
    n: [260, 14, 38, 6],
    caption: 'A pot of this costs about the same as one takeaway coffee and feeds six.',
    daysAgo: 13,
  },
  {
    emoji: '🍞',
    title: 'Caprese farro salad',
    summary: 'Chewy farro with tomatoes, mozzarella, basil and a balsamic glaze — caprese that fills you up.',
    cuisine: 'Italian',
    meal: 'lunch',
    serves: 4,
    total: 35,
    active: 15,
    level: 'easy',
    diet: ['vegetarian', 'nut-free'],
    tags: ['grain-bowl', 'summer', 'meal-prep'],
    allergens: ['gluten'],
    equipment: ['pot'],
    techniques: ['boiling', 'reducing'],
    ing: ['250 g farro', 'salt', '300 g cherry tomatoes, halved', '200 g mozzarella, torn', '1 bunch basil', '3 tbsp olive oil', '2 tbsp balsamic', '1 clove garlic, minced', 'black pepper'],
    steps: [
      ['Cook the farro', 'Boil the farro in salted water until tender but chewy, then drain and spread on a tray to cool a little.', 1500],
      ['Reduce the balsamic', 'Simmer the balsamic in a small pan until syrupy — about a tablespoon left.', 240, 'Medium heat'],
      ['Assemble', 'Toss the farro with olive oil, garlic, tomatoes, salt and pepper. Fold in the mozzarella and most of the basil. Drizzle with the balsamic and top with the remaining leaves.'],
    ],
    subs: [['farro', 'quinoa or brown rice', 'makes it gluten-free']],
    storage: '2 days; add basil fresh.',
    n: [480, 20, 54, 20],
    caption: 'Caprese, but lunch-sized.',
    daysAgo: 12,
  },
  {
    emoji: '🐟',
    title: 'Tuna niçoise bowl',
    summary: 'Green beans, potatoes, eggs, olives and good tinned tuna with a mustardy dressing. Everything cooks in one pot of water.',
    cuisine: 'French',
    meal: 'lunch',
    serves: 2,
    total: 30,
    active: 20,
    level: 'easy',
    diet: ['pescatarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['one-pot', 'classic', 'meal-prep'],
    equipment: ['pot'],
    techniques: ['boiling', 'blanching'],
    ing: ['300 g potato, halved if small', '2 eggs', '150 g green beans, trimmed', '1 can tuna, drained', '60 g olives', '150 g cherry tomatoes, halved', '2 handfuls lettuce', 'Dressing: 3 tbsp olive oil', 'Dressing: 1 tbsp vinegar', 'Dressing: 1 tsp dijon', 'Dressing: 1 tsp capers, chopped', 'salt', 'black pepper'],
    steps: [
      ['One pot, three things', 'Boil the potatoes in salted water. After 8 minutes add the eggs; after another 4 minutes add the green beans. Two minutes later, drain everything and drop the eggs into cold water.', 840, null, 'Eggs at 7 minutes total give a just-set yolk.'],
      ['Dress', 'Whisk the olive oil, vinegar, dijon, capers, salt and pepper.'],
      ['Build the bowls', 'Peel and halve the eggs. Arrange lettuce, warm potatoes, beans, tomatoes, olives and tuna in bowls, top with egg and spoon over the dressing.'],
    ],
    subs: [['tuna', 'seared fresh tuna or chickpeas']],
    n: [520, 34, 36, 26],
    caption: 'Niçoise, weeknight edition: everything in one pot of boiling water.',
    daysAgo: 11,
  },
  {
    emoji: '🥬',
    title: 'Thai larb gai lettuce cups',
    summary: 'Ground chicken tossed hot with lime, fish sauce, chili, herbs and toasted rice powder, scooped up in crisp lettuce.',
    cuisine: 'Thai',
    meal: 'lunch',
    serves: 3,
    total: 25,
    active: 25,
    level: 'easy',
    diet: ['gluten-free', 'dairy-free', 'nut-free', 'high-protein', 'low-carb'],
    tags: ['quick', 'spicy', 'fresh', 'herbs'],
    equipment: ['skillet'],
    techniques: ['toasting', 'stir-frying'],
    ing: ['2 tbsp rice', '1 tbsp vegetable oil', '500 g ground chicken', '2 shallots, thinly sliced', '3 tbsp fish sauce', '2 limes, juiced', '1 tsp sugar', '1 tsp chili flakes', '1 bunch mint', '1 bunch cilantro', '4 spring onions, sliced', '1 head lettuce, leaves separated'],
    steps: [
      ['Toast the rice', 'Toast the raw rice in a dry skillet, shaking often, until deep golden and nutty. Grind coarsely in a mortar or spice grinder.', 300, 'Medium heat', 'This khao khua is what makes larb taste like larb.'],
      ['Cook the chicken', 'Heat the oil and cook the chicken, breaking it up, until just cooked through and no longer pink. Do not brown it hard — larb is tender, not crispy.', 360, 'Medium-high heat'],
      ['Dress hot', 'Off the heat, stir in the shallots, fish sauce, lime juice, sugar and chili flakes. Taste: it should be sharp, salty and hot in equal measure.'],
      ['Herbs and serve', 'Fold in the mint, cilantro, spring onions and toasted rice. Serve warm with lettuce leaves for scooping.'],
    ],
    subs: [['ground chicken', 'ground pork or crumbled tofu'], ['fish sauce', 'tamari plus a pinch of salt', 'for vegan']],
    n: [330, 36, 10, 16],
    caption: 'Larb. Do not skip the toasted rice.',
    daysAgo: 10,
  },
  {
    emoji: '🧆',
    title: 'Crispy falafel wraps',
    summary: 'Falafel from dried chickpeas — the only way they stay crisp — with tahini sauce, pickles and herbs in warm pita.',
    cuisine: 'Levantine',
    meal: 'lunch',
    serves: 4,
    total: 45,
    active: 40,
    level: 'medium',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['street-food', 'crispy', 'project'],
    allergens: ['sesame', 'gluten'],
    equipment: ['food processor', 'deep skillet'],
    techniques: ['frying'],
    ing: ['250 g chickpeas, dried and soaked overnight', '1 onion, roughly chopped', '4 cloves garlic', '1 bunch parsley', '1 bunch cilantro', '2 tsp cumin', '1 tsp coriander seed, ground', '1 tsp salt', '1/2 tsp baking soda', '2 tbsp flour', '500 ml vegetable oil, for frying', 'Sauce: 4 tbsp tahini', 'Sauce: 1 lemon, juiced', 'Sauce: 1 clove garlic, minced', '4 pita', '1 cucumber, sliced', '2 tomatoes, sliced', '?pickles'],
    steps: [
      ['Grind the mix', 'Drain the soaked chickpeas well (do not cook them). Pulse in a food processor with the onion, garlic, herbs, cumin, coriander and salt until it looks like coarse wet sand that holds together when squeezed. Stir in the baking soda and flour. Chill 30 minutes.', 1800, null, 'Canned chickpeas will fall apart in the oil; dried is essential.'],
      ['Make the tahini sauce', 'Whisk the tahini with lemon juice, garlic, a pinch of salt and enough cold water to make it pourable.'],
      ['Fry', 'Heat 3 cm of oil to 180°C. Shape walnut-sized balls, slightly flattened, and fry in batches until deep brown and crisp.', 240, 'Oil at 180°C / 350°F', 'Test one first; if it breaks apart, add another tablespoon of flour.'],
      ['Wrap', 'Warm the pita. Fill with falafel, cucumber, tomato and pickles and drown in tahini sauce.'],
    ],
    subs: [['pita', 'lettuce leaves or gluten-free flatbread']],
    makeAhead: 'The uncooked mix keeps 2 days in the fridge; fry to order.',
    n: [560, 20, 70, 24],
    caption: 'Falafel from dried chickpeas. Once you try it you will not go back.',
    daysAgo: 9,
  },
  {
    emoji: '🍲',
    title: 'Miso soup with tofu and soba',
    summary: 'A proper bowl of miso soup made a meal with soba noodles, silken tofu, greens and spring onion. Ten minutes, honestly.',
    cuisine: 'Japanese',
    meal: 'lunch',
    serves: 2,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free'],
    tags: ['quick', 'light', 'noodles', 'soothing'],
    allergens: ['soy', 'gluten'],
    equipment: ['pot'],
    techniques: ['simmering'],
    ing: ['150 g soba noodles', '800 ml stock', '3 tbsp miso', '200 g tofu, silken, cubed', '2 handfuls spinach', '2 spring onions, sliced', '1 tsp sesame oil', '?1 sheet nori, snipped', '?chili oil'],
    steps: [
      ['Cook the soba', 'Boil the soba in plenty of water until just tender, drain and rinse briefly under cold water.', 300],
      ['Warm the broth', 'Bring the stock to just below a simmer. Whisk the miso with a ladle of hot stock in a cup until smooth, then stir it back in. Do not boil after adding miso.', 180, 'Low heat', 'Boiling dulls miso and kills its aroma.'],
      ['Assemble', 'Add the tofu and spinach to the broth for a minute to warm. Divide the soba between bowls, ladle over the soup, and top with spring onion, sesame oil, nori and chili oil.'],
    ],
    subs: [['soba', '100% buckwheat soba or rice noodles', 'gluten-free']],
    n: [390, 20, 56, 9],
    caption: 'Miso soup, upgraded to lunch.',
    daysAgo: 8,
  },
  {
    emoji: '🥙',
    title: 'Peruvian-style quinoa salad with lime and corn',
    summary: 'Quinoa with charred corn, black beans, avocado and a lime-cilantro dressing, plus a little heat from a fresh chili.',
    cuisine: 'Peruvian',
    meal: 'lunch',
    serves: 4,
    total: 30,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['grain-bowl', 'meal-prep', 'summer'],
    equipment: ['pot', 'skillet'],
    techniques: ['charring', 'dressing'],
    ing: ['200 g quinoa', '1 tbsp vegetable oil', '200 g corn', '1 can black beans, drained', '1 avocado, diced', '1/2 red onion, finely chopped', '1 chili, finely chopped', '1 bunch cilantro, chopped', 'Dressing: 3 tbsp olive oil', 'Dressing: 2 limes, juiced', 'Dressing: 1/2 tsp cumin', 'salt'],
    steps: [
      ['Cook the quinoa', 'Rinse the quinoa, then simmer in 400 ml salted water, covered, until the water is absorbed. Rest 5 minutes off the heat, then fluff.', 900, 'Low heat'],
      ['Char the corn', 'Heat the oil in a skillet until smoking and cook the corn without stirring much until blistered and blackened in spots.', 300, 'High heat'],
      ['Toss', 'Whisk the dressing. Combine the quinoa, corn, beans, onion, chili and cilantro with the dressing and season. Fold in the avocado last so it stays whole.'],
    ],
    n: [430, 15, 58, 16],
    caption: 'Char the corn until it scares you a little. That is the flavour.',
    daysAgo: 7,
  },
  // ---------------------------------------------------------------- dinner
  {
    emoji: '🍝',
    title: 'Spaghetti aglio e olio',
    summary: 'Garlic, olive oil, chili and parsley — four ingredients and a technique. The starchy pasta water turns the oil into a sauce.',
    cuisine: 'Italian',
    meal: 'dinner',
    serves: 2,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free'],
    tags: ['pantry', 'quick', 'budget', 'late-night'],
    allergens: ['gluten'],
    equipment: ['large pot', 'skillet'],
    techniques: ['emulsifying'],
    ing: ['200 g pasta, spaghetti', 'salt', '5 tbsp olive oil', '6 cloves garlic, thinly sliced', '1/2 tsp chili flakes', '1 handful parsley, chopped', '?1 lemon, zested', '?parmesan'],
    steps: [
      ['Boil the pasta', 'Cook the spaghetti in well-salted boiling water until just shy of al dente. Scoop out a mug of the water before draining.', 540, 'High heat'],
      ['Toast the garlic', 'Meanwhile warm the olive oil and garlic in a skillet over low heat. Cook gently until the garlic is pale gold and smells sweet, then add the chili flakes. Do not let it brown.', 300, 'Low heat', 'Brown garlic turns bitter; pull it early.'],
      ['Emulsify', 'Add the drained pasta and a splash of the starchy water to the skillet. Toss hard over medium heat for a minute — the water and oil come together into a glossy coating.', 60, 'Medium heat'],
      ['Finish', 'Toss through the parsley and lemon zest. Salt to taste. Parmesan if you are not keeping it vegan.'],
    ],
    subs: [['spaghetti', 'gluten-free spaghetti', 'use a little less pasta water']],
    n: [560, 13, 72, 26],
    caption: 'What to cook when there is nothing in the house.',
    daysAgo: 22,
  },
  {
    emoji: '🍛',
    title: 'Chicken tikka masala',
    summary: 'Yogurt-marinated chicken charred under the grill, then simmered in a tomato, cream and garam masala sauce. Better than the takeaway.',
    cuisine: 'Indian',
    meal: 'dinner',
    serves: 4,
    total: 60,
    active: 35,
    level: 'medium',
    diet: ['gluten-free', 'nut-free', 'halal', 'high-protein'],
    tags: ['curry', 'crowd-pleaser', 'marinade'],
    equipment: ['grill or broiler', 'large pan'],
    techniques: ['marinating', 'broiling', 'simmering'],
    ing: ['Marinade: 600 g chicken thigh, cut into chunks', 'Marinade: 150 g yogurt', 'Marinade: 1 lemon, juiced', 'Marinade: 2 tsp cumin', 'Marinade: 2 tsp paprika', 'Marinade: 1 tsp turmeric', 'Marinade: 1 tsp salt', 'Sauce: 2 tbsp butter', 'Sauce: 1 onion, finely diced', 'Sauce: 4 cloves garlic, minced', 'Sauce: 1 thumb ginger, grated', 'Sauce: 2 tsp curry powder', 'Sauce: 1 tsp cumin', 'Sauce: 400 g canned tomatoes', 'Sauce: 150 ml heavy cream', 'Sauce: 1 tsp sugar', 'salt', '1 bunch cilantro', 'rice, to serve'],
    steps: [
      ['Marinate', 'Mix the chicken with the yogurt, lemon juice, cumin, paprika, turmeric and salt. Leave at least 30 minutes, or overnight.', 1800],
      ['Char the chicken', 'Spread the chicken on a tray and grill close to the heat until charred at the edges and just cooked. It will finish in the sauce.', 600, 'Grill on high', 'A little blackening is flavour, not a mistake.'],
      ['Build the sauce', 'Melt the butter and cook the onion until golden. Add the garlic, ginger, curry powder and cumin for a minute, then the tomatoes. Simmer until thick and darkened.', 900, 'Medium heat'],
      ['Combine', 'Blend the sauce smooth if you like, then stir in the cream, sugar and the chicken with its juices. Simmer gently until the chicken is tender. Salt to taste.', 480, 'Low heat'],
      ['Serve', 'Scatter with cilantro and serve over rice.'],
    ],
    subs: [['heavy cream', 'coconut milk', 'dairy-free, slightly sweeter'], ['chicken thigh', 'paneer or chickpeas', 'vegetarian']],
    storage: 'Even better the next day. 3 days in the fridge, freezes well.',
    n: [520, 40, 16, 32],
    caption: 'The Friday-night curry. Marinate in the morning if you can.',
    daysAgo: 21,
  },
  {
    emoji: '🥩',
    title: 'Beef bulgogi rice bowls',
    summary: 'Thin-sliced beef in a sweet-savory soy, pear and sesame marinade, seared hard and piled on rice with quick pickles.',
    cuisine: 'Korean',
    meal: 'dinner',
    serves: 4,
    total: 40,
    active: 25,
    level: 'easy',
    diet: ['dairy-free', 'nut-free', 'high-protein'],
    tags: ['stir-fry', 'rice-bowl', 'marinade', 'weeknight'],
    allergens: ['soy', 'sesame'],
    equipment: ['skillet', 'rice cooker or pot'],
    techniques: ['marinating', 'searing'],
    ing: ['600 g beef steak, very thinly sliced', 'Marinade: 4 tbsp soy sauce', 'Marinade: 2 tbsp brown sugar', 'Marinade: 1 pear, grated', 'Marinade: 4 cloves garlic, minced', 'Marinade: 1 tbsp sesame oil', 'Marinade: 1 tsp black pepper', '1 tbsp vegetable oil', '300 g rice', '1 cucumber, thinly sliced', '2 tbsp rice vinegar', '4 spring onions, sliced', '1 tbsp sesame seeds, toasted', '?gochujang'],
    steps: [
      ['Marinate', 'Mix the beef with the soy sauce, brown sugar, grated pear, garlic, sesame oil and pepper. 20 minutes is enough; the pear tenderizes fast.', 1200, null, 'Freeze the steak for 30 minutes first and it slices paper-thin.'],
      ['Rice and pickles', 'Cook the rice. Toss the cucumber with the rice vinegar and a pinch of salt and set aside.', 1080],
      ['Sear in batches', 'Get a skillet smoking hot with the oil. Cook the beef in two or three batches, spread out, without moving it for the first minute so it chars.', 240, 'Very high heat', 'Crowding the pan steams the beef instead of searing it.'],
      ['Bowl it', 'Rice, beef, pickled cucumber, spring onions, sesame seeds. Gochujang on the side.'],
    ],
    subs: [['soy sauce', 'tamari', 'gluten-free'], ['beef', 'thin pork shoulder or firm tofu']],
    n: [610, 38, 66, 20],
    caption: 'Bulgogi bowls. The grated pear is doing more than you think.',
    daysAgo: 20,
  },
  {
    emoji: '🍜',
    title: 'Tofu pad thai',
    summary: 'Chewy rice noodles with crispy tofu, egg-free and fully plant-based, in a tamarind-lime sauce with peanuts and bean sprouts.',
    cuisine: 'Thai',
    meal: 'dinner',
    serves: 2,
    total: 30,
    active: 30,
    level: 'medium',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    tags: ['noodles', 'stir-fry', 'street-food'],
    allergens: ['peanuts', 'soy'],
    equipment: ['wok or large skillet'],
    techniques: ['stir-frying'],
    ing: ['200 g rice noodles', '300 g tofu, firm, cubed', '2 tbsp cornstarch', '3 tbsp vegetable oil', '3 cloves garlic, minced', '3 spring onions, cut into lengths', 'Sauce: 2 tbsp tamarind paste', 'Sauce: 2 tbsp tamari', 'Sauce: 1.5 tbsp brown sugar', 'Sauce: 1 lime, juiced', 'Sauce: 1 tsp chili flakes', '100 g bean sprouts', '3 tbsp peanuts, crushed', '1 lime, cut into wedges'],
    steps: [
      ['Soak the noodles', 'Soak the rice noodles in hot (not boiling) water until pliable but still firm, then drain. They finish cooking in the wok.', 480],
      ['Crisp the tofu', 'Toss the tofu in cornstarch. Fry in 2 tablespoons of oil until golden and crisp on all sides. Set aside.', 420, 'Medium-high heat'],
      ['Stir-fry', 'Whisk the sauce. Heat the remaining oil, add the garlic and spring onions for 30 seconds, then the noodles and sauce. Toss constantly until the noodles are tender and glossy.', 180, 'High heat', 'If they stick, splash in a tablespoon of water.'],
      ['Finish', 'Fold in the tofu and bean sprouts. Serve with crushed peanuts and lime wedges.'],
    ],
    subs: [['tamarind paste', '1 tbsp lime juice + 1 tbsp brown sugar'], ['peanuts', 'toasted cashews or omit', 'nut-free']],
    n: [640, 24, 82, 24],
    caption: 'Pad thai without the egg or fish sauce — and nobody asks.',
    daysAgo: 19,
  },
  {
    emoji: '🫕',
    title: 'Moroccan chickpea and apricot tagine',
    summary: 'Chickpeas, sweet potato and dried apricots in a warm ras el hanout–style sauce. Hands-off simmering, big flavour, couscous on the side.',
    cuisine: 'Moroccan',
    meal: 'dinner',
    serves: 4,
    total: 50,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['stew', 'one-pot', 'big-batch', 'freezer-friendly'],
    equipment: ['large pot or tagine'],
    techniques: ['braising'],
    ing: ['2 tbsp olive oil', '1 onion, diced', '3 cloves garlic, minced', '2 tsp cumin', '2 tsp coriander seed, ground', '1 tsp cinnamon', '1 tsp turmeric', '1/2 tsp cayenne', '1 sweet potato, cubed', '2 cans chickpeas, drained', '400 g canned tomatoes', '400 ml stock', '80 g dates, chopped', 'salt', '1 bunch cilantro', '1 lemon, cut into wedges', '?couscous, to serve'],
    steps: [
      ['Start the base', 'Soften the onion in the oil with a pinch of salt. Add the garlic and all the spices and cook for a minute until the kitchen smells like a market.', 420, 'Medium heat'],
      ['Simmer', 'Add the sweet potato, chickpeas, tomatoes, stock and dates. Bring to a boil, then cover and simmer until the sweet potato is tender and the sauce has thickened.', 1800, 'Low heat', 'Lid off for the last 10 minutes if it looks thin.'],
      ['Season and serve', 'Salt to taste — the dates need it. Scatter cilantro and serve with lemon wedges and couscous or rice.'],
    ],
    subs: [['dates', 'dried apricots or raisins'], ['couscous', 'rice or quinoa', 'gluten-free']],
    storage: 'Freezes for 3 months.',
    n: [410, 14, 66, 10],
    caption: 'Tagine without the tagine. Dates instead of apricots because that is what we had.',
    daysAgo: 18,
  },
  {
    emoji: '🐟',
    title: 'Salmon teriyaki with sesame greens',
    summary: 'Salmon glazed in a three-ingredient teriyaki, with quick-steamed greens and rice. Fifteen minutes from fridge to table.',
    cuisine: 'Japanese',
    meal: 'dinner',
    serves: 2,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['pescatarian', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['quick', 'weeknight', 'glaze'],
    allergens: ['soy', 'sesame'],
    equipment: ['skillet', 'pot'],
    techniques: ['pan-searing', 'glazing', 'steaming'],
    ing: ['2 fillets salmon', '1 tbsp vegetable oil', 'Glaze: 3 tbsp soy sauce', 'Glaze: 2 tbsp honey', 'Glaze: 1 tbsp rice vinegar', 'Glaze: 1 clove garlic, grated', '200 g broccoli, cut into florets', '1 tsp sesame oil', '1 tsp sesame seeds', '150 g rice, cooked'],
    steps: [
      ['Sear the salmon', 'Pat the salmon dry. Sear skin-side down in the oil until the skin is crisp, then flip for a minute.', 300, 'Medium-high heat'],
      ['Glaze', 'Pour in the soy sauce, honey, vinegar and garlic. Let it bubble and reduce, spooning it over the fish, until sticky and the salmon is just cooked through.', 180, 'Medium heat', 'Pull the salmon while the centre is still slightly translucent.'],
      ['Greens', 'Steam or boil the broccoli for 3 minutes, drain, and toss with the sesame oil and seeds.', 180],
      ['Plate', 'Rice, greens, salmon, and every drop of glaze from the pan.'],
    ],
    subs: [['honey', 'maple syrup', 'vegan-friendly glaze for tofu'], ['soy sauce', 'tamari', 'gluten-free']],
    n: [580, 38, 52, 22],
    caption: 'Teriyaki salmon is a fifteen-minute dinner if you make the rice first.',
    daysAgo: 17,
  },
  {
    emoji: '🫘',
    title: 'Ethiopian red lentils (misir wot)',
    summary: 'Red lentils simmered with berbere spice, onions cooked long and slow, and a finish of garlic and ginger. Eat with flatbread or rice.',
    cuisine: 'Ethiopian',
    meal: 'dinner',
    serves: 4,
    total: 45,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['stew', 'spicy', 'budget', 'big-batch'],
    equipment: ['pot'],
    techniques: ['slow-cooking onions', 'simmering'],
    ing: ['3 tbsp vegetable oil', '2 onions, finely diced', '3 cloves garlic, minced', '1 thumb ginger, grated', '2 tbsp paprika', '1 tsp cayenne', '1 tsp cumin', '1/2 tsp cinnamon', '1/4 tsp nutmeg', '2 tbsp tomato paste', '250 g lentils, red', '900 ml stock', 'salt', '?flatbread or rice'],
    steps: [
      ['Cook the onions properly', 'Cook the onions in the oil over medium-low heat, stirring now and then, until deeply soft and golden. This is the backbone; give it the full time.', 900, 'Medium-low heat'],
      ['Spice', 'Add the garlic, ginger, paprika, cayenne, cumin, cinnamon, nutmeg and tomato paste. Stir for 2 minutes, adding a splash of water if it catches.', 120],
      ['Simmer the lentils', 'Add the lentils and stock. Simmer, stirring occasionally, until the lentils are soft and the stew is thick enough to scoop with bread.', 1500, 'Low heat', 'Red lentils dissolve; that is the texture you want.'],
      ['Season', 'Salt generously. Serve with flatbread or rice.'],
    ],
    subs: [['paprika + cayenne', '2 tbsp berbere', 'the real thing, if you can find it']],
    storage: 'Thickens overnight; loosen with water. 4 days in the fridge.',
    n: [330, 17, 44, 10],
    caption: 'Misir wot. Cook the onions longer than feels reasonable.',
    daysAgo: 16,
  },
  {
    emoji: '🍗',
    title: 'Jamaican jerk chicken with rice and peas',
    summary: 'Chicken thighs in a fiery allspice, thyme and scallion marinade, roasted until charred, with coconut rice and kidney beans.',
    cuisine: 'Jamaican',
    meal: 'dinner',
    serves: 4,
    total: 70,
    active: 30,
    level: 'medium',
    diet: ['gluten-free', 'dairy-free', 'nut-free', 'halal', 'high-protein'],
    tags: ['roast', 'spicy', 'marinade', 'sunday'],
    allergens: ['soy'],
    equipment: ['blender', 'roasting tray', 'pot'],
    techniques: ['marinating', 'roasting'],
    ing: ['Marinade: 8 chicken thigh, bone-in', 'Marinade: 4 spring onions', 'Marinade: 2 chili, or more', 'Marinade: 3 cloves garlic', 'Marinade: 1 thumb ginger', 'Marinade: 1 tbsp thyme', 'Marinade: 1 tbsp allspice, ground', 'Marinade: 1 tsp cinnamon', 'Marinade: 1/2 tsp nutmeg', 'Marinade: 2 tbsp soy sauce', 'Marinade: 2 tbsp brown sugar', 'Marinade: 1 lime, juiced', 'Marinade: 2 tbsp vegetable oil', 'Rice: 300 g rice', 'Rice: 400 ml coconut milk', 'Rice: 1 can kidney beans, drained', 'Rice: 2 sprigs thyme', 'Rice: 1 spring onion, whole', 'salt'],
    steps: [
      ['Blend the jerk', 'Blend the spring onions, chilies, garlic, ginger, thyme, allspice, cinnamon, nutmeg, soy sauce, brown sugar, lime juice and oil into a rough paste. Rub all over the chicken and marinate at least 1 hour, ideally overnight.', 3600, null, 'Wear gloves for the chilies if they are the hot kind.'],
      ['Roast', 'Roast the chicken skin-side up on a tray until deeply browned and cooked through — the juices run clear and the edges char.', 2400, 'Oven 220°C / 425°F'],
      ['Rice and peas', 'Rinse the rice and put it in a pot with the coconut milk, 200 ml water, kidney beans, thyme, the whole spring onion and a big pinch of salt. Bring to a boil, cover, and cook on the lowest heat until the liquid is absorbed. Rest 10 minutes, fluff.', 1200, 'Lowest heat'],
      ['Serve', 'Chicken over rice, with any tray juices poured over.'],
    ],
    subs: [['chicken thigh', 'cauliflower steaks', 'roast 25 minutes for a vegan version'], ['soy sauce', 'tamari', 'gluten-free']],
    n: [720, 44, 62, 30],
    caption: 'Jerk chicken from the oven. Marinate overnight and thank yourself tomorrow.',
    daysAgo: 15,
  },
  {
    emoji: '🍄',
    title: 'Mushroom risotto',
    summary: 'Arborio rice stirred slowly with stock and a heap of browned mushrooms, finished with butter and parmesan. Half an hour of pleasant stirring.',
    cuisine: 'Italian',
    meal: 'dinner',
    serves: 4,
    total: 45,
    active: 40,
    level: 'medium',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['comfort', 'classic', 'date-night'],
    equipment: ['wide pan', 'skillet'],
    techniques: ['sautéing', 'risotto method'],
    ing: ['3 tbsp butter', '400 g mushroom, sliced', '1 tbsp olive oil', '1 onion, finely diced', '2 cloves garlic, minced', '300 g arborio rice', '150 ml white wine', '1.2 l stock, hot', '60 g parmesan, grated', 'salt', 'black pepper', '1 handful parsley, chopped', '?1 tsp thyme'],
    steps: [
      ['Brown the mushrooms', 'Cook the mushrooms in 1 tablespoon of butter in a hot skillet, in two batches, until deeply golden. Salt at the end, not the start. Set aside.', 600, 'High heat', 'Salting early draws out water and stops browning.'],
      ['Start the rice', 'In a wide pan, soften the onion in the olive oil and 1 tablespoon of butter. Add the garlic and rice and stir until the grains turn translucent at the edges.', 240, 'Medium heat'],
      ['Wine, then stock', 'Pour in the wine and stir until absorbed. Add hot stock a ladle at a time, stirring often and waiting until each addition is nearly absorbed before the next. Keep going until the rice is tender with a slight bite.', 1200, 'Medium-low heat', 'It should flow like lava when you shake the pan, not sit in a mound.'],
      ['Mantecatura', 'Off the heat, beat in the last of the butter, the parmesan and the mushrooms. Cover for 2 minutes, then season and finish with parsley and pepper.', 120],
    ],
    subs: [['white wine', 'a squeeze of lemon and more stock'], ['parmesan', 'nutritional yeast + olive oil', 'vegan']],
    n: [520, 14, 66, 20],
    caption: 'Risotto is not hard, it is just thirty minutes of standing there. Bring a podcast.',
    daysAgo: 14,
  },
  {
    emoji: '🥒',
    title: 'Zucchini lasagna (low-carb)',
    summary: 'Planks of salted zucchini stand in for pasta between a rich beef ragù and ricotta. All the lasagna comfort at a fraction of the carbs.',
    cuisine: 'Italian-American',
    meal: 'dinner',
    serves: 6,
    total: 90,
    active: 40,
    level: 'medium',
    diet: ['gluten-free', 'keto-friendly', 'low-carb', 'nut-free', 'high-protein'],
    tags: ['bake', 'meal-prep', 'comfort'],
    equipment: ['baking dish', 'large pan'],
    techniques: ['salting vegetables', 'braising', 'baking'],
    ing: ['4 zucchini, sliced lengthwise 5 mm thick', '1 tsp salt', '1 tbsp olive oil', '1 onion, diced', '3 cloves garlic, minced', '600 g ground beef', '2 tbsp tomato paste', '400 g canned tomatoes', '1 tsp oregano', 'black pepper', '400 g ricotta', '1 egg', '150 g mozzarella, grated', '40 g parmesan, grated', '1 handful basil'],
    steps: [
      ['Salt the zucchini', 'Lay the zucchini planks on trays, salt both sides, and leave 20 minutes. Pat very dry. This is what keeps the lasagna from turning to soup.', 1200, null, 'Grill or dry-fry the planks for 2 minutes a side for an even firmer result.'],
      ['Make the ragù', 'Brown the onion in the oil, add the garlic and beef and cook until the beef is browned and any liquid has evaporated. Stir in the tomato paste, tomatoes, oregano, salt and pepper and simmer until thick.', 1500, 'Medium heat'],
      ['Layer', 'Mix the ricotta with the egg and a pinch of salt. In a baking dish: ragù, zucchini planks, ricotta, mozzarella; repeat, finishing with mozzarella and parmesan.'],
      ['Bake', 'Bake uncovered until bubbling and browned on top. Rest 15 minutes before slicing — it firms up as it cools.', 2400, 'Oven 190°C / 375°F'],
    ],
    subs: [['ground beef', 'ground turkey or lentils'], ['ricotta', 'cottage cheese, blended smooth']],
    storage: 'Slices reheat well for 4 days and freeze for 2 months.',
    n: [430, 36, 12, 26],
    caption: 'Lasagna that skips the pasta and nobody minds. Salt the zucchini — do not skip it.',
    daysAgo: 13,
  },
  {
    emoji: '🍋',
    title: 'Lemon herb roast chicken with potatoes',
    summary: 'A whole chicken over potatoes that cook in its juices, with lemon, garlic and rosemary. The Sunday recipe everyone should own.',
    cuisine: 'French',
    meal: 'dinner',
    serves: 4,
    total: 100,
    active: 20,
    level: 'medium',
    diet: ['gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['roast', 'sunday', 'one-tray', 'classic'],
    equipment: ['roasting tray'],
    techniques: ['roasting', 'resting'],
    ing: ['1 whole chicken, about 1.6 kg', '1 kg potato, halved', '1 lemon, halved', '4 cloves garlic, crushed', '3 sprigs rosemary', '3 tbsp olive oil', 'salt', 'black pepper', '?1 onion, cut into wedges'],
    steps: [
      ['Prep', 'Pat the chicken dry inside and out. Rub with 1 tablespoon of oil, then salt and pepper generously, including inside. Stuff the cavity with half the lemon, the garlic and a sprig of rosemary.', null, null, 'Salting an hour ahead, uncovered in the fridge, gives crisper skin.'],
      ['Tray up', 'Toss the potatoes (and onion) with the remaining oil, salt, the rest of the rosemary and the other lemon half squeezed over. Spread on a tray and set the chicken on top, breast up.'],
      ['Roast', 'Roast until the skin is deep golden and the thickest part of the thigh reads 74°C / 165°F, or the juices run clear. Turn the potatoes once halfway.', 4500, 'Oven 200°C / 400°F'],
      ['Rest', 'Lift the chicken onto a board and rest 15 minutes. Return the potatoes to the oven to crisp while it rests.', 900],
      ['Carve', 'Carve and serve with the potatoes and every bit of the tray juices.'],
    ],
    subs: [['rosemary', 'thyme or oregano'], ['potatoes', 'sweet potato and carrots']],
    n: [680, 52, 40, 34],
    caption: 'One tray, one chicken, one hour and a half. The potatoes are the best part.',
    daysAgo: 12,
  },
  {
    emoji: '🌮',
    title: 'Black bean tacos with pickled red onion',
    summary: 'Smoky spiced black beans in warm corn tortillas with quick-pickled onion, avocado and lime. Fifteen minutes, mostly pantry.',
    cuisine: 'Mexican',
    meal: 'dinner',
    serves: 3,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['quick', 'pantry', 'budget', 'weeknight'],
    equipment: ['skillet'],
    techniques: ['quick pickling', 'sautéing'],
    ing: ['1 red onion, thinly sliced', '2 limes, juiced', 'salt', '1 tbsp vegetable oil', '2 cloves garlic, minced', '2 tsp cumin', '1 tsp chili powder', '1 tsp paprika', '2 cans black beans, drained', '9 tortilla, corn', '1 avocado, sliced', '1 bunch cilantro', '?hot sauce'],
    steps: [
      ['Pickle', 'Toss the red onion with the juice of one lime and a pinch of salt. Leave while you cook.', 600],
      ['Spice the beans', 'Warm the oil, add the garlic, cumin, chili powder and paprika for 30 seconds, then the beans with a splash of water. Simmer, mashing a few beans against the pan so they get saucy. Season with salt and the second lime.', 360, 'Medium heat'],
      ['Warm the tortillas', 'Char the tortillas directly over a gas flame or in a dry hot pan, 20 seconds a side. Keep them wrapped in a towel.', 120, 'High heat'],
      ['Build', 'Beans, avocado, pickled onion, cilantro, hot sauce. Eat immediately.'],
    ],
    subs: [['corn tortillas', 'lettuce cups', 'lower carb'], ['avocado', 'a spoon of sour cream', 'not vegan']],
    n: [480, 18, 74, 14],
    caption: 'Tuesday tacos. The pickled onion takes ten minutes and changes everything.',
    daysAgo: 11,
  },
  {
    emoji: '🍷',
    title: 'Coq au vin',
    summary: 'Chicken thighs braised in red wine with bacon, mushrooms and pearl onions. A slow, generous, deeply French pot.',
    cuisine: 'French',
    meal: 'dinner',
    serves: 4,
    total: 105,
    active: 40,
    level: 'hard',
    diet: ['gluten-free', 'nut-free', 'high-protein'],
    tags: ['braise', 'weekend', 'classic', 'wine'],
    equipment: ['dutch oven'],
    techniques: ['browning', 'deglazing', 'braising'],
    ing: ['8 chicken thigh, bone-in, skin on', 'salt', 'black pepper', '150 g bacon, chopped', '1 tbsp olive oil', '250 g mushroom, halved', '12 shallots, peeled', '2 cloves garlic, minced', '2 tbsp tomato paste', '500 ml red wine', '300 ml stock', '2 bay leaf', '2 sprigs thyme', '2 tbsp butter', '1 tbsp cornstarch', '1 handful parsley, chopped'],
    steps: [
      ['Brown everything', 'Season the chicken. In a dutch oven, crisp the bacon in the oil and set aside. Brown the chicken skin-side down in the fat until golden, then remove. Brown the mushrooms and shallots in the same pot.', 1200, 'Medium-high heat', 'Browning is flavour; do not rush this stage.'],
      ['Deglaze', 'Stir in the garlic and tomato paste, then pour in the wine and scrape up everything stuck to the pot. Add the stock, bay leaves and thyme.', 120],
      ['Braise', 'Return the chicken and bacon. Cover and simmer very gently until the chicken is tender and pulling from the bone.', 2700, 'Low heat'],
      ['Finish the sauce', 'Lift out the chicken. Whisk the cornstarch with a splash of water and stir into the sauce with the butter; simmer until glossy and thick enough to coat a spoon. Season, return the chicken, scatter parsley.', 300, 'Medium heat'],
    ],
    subs: [['red wine', 'more stock plus 1 tbsp balsamic', 'alcohol-free'], ['bacon', 'smoked tofu, cubed']],
    makeAhead: 'Better on day two. Cool, refrigerate, reheat gently.',
    n: [620, 46, 14, 36],
    caption: 'Coq au vin for a rainy Saturday. Open the wine at step one.',
    daysAgo: 10,
  },
  {
    emoji: '🥘',
    title: 'Seafood paella',
    summary: 'Saffron rice with shrimp, mussels and squid cooked in a wide pan until a crust forms underneath. Do not stir. Trust the pan.',
    cuisine: 'Spanish',
    meal: 'dinner',
    serves: 4,
    total: 55,
    active: 40,
    level: 'hard',
    diet: ['pescatarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['showpiece', 'one-pan', 'weekend'],
    equipment: ['paella pan or wide skillet'],
    techniques: ['sofrito', 'absorption cooking'],
    ing: ['3 tbsp olive oil', '1 onion, finely diced', '1 bell pepper, diced', '4 cloves garlic, minced', '2 tomatoes, grated', '1 tsp paprika', 'pinch saffron', '350 g arborio rice', '1 l stock, hot', 'salt', '300 g shrimp', '300 g mussels, cleaned', '200 g squid, sliced into rings', '100 g peas', '1 lemon, cut into wedges', '1 handful parsley, chopped'],
    steps: [
      ['Sofrito', 'Cook the onion and pepper slowly in the oil until very soft. Add the garlic, grated tomato and paprika and cook down to a thick paste.', 900, 'Medium-low heat'],
      ['Rice and stock', 'Stir the saffron into the hot stock. Add the rice to the pan and stir once to coat, then pour in the stock, season, and spread the rice evenly. From now on, do not stir.', 60, 'High heat'],
      ['Cook', 'Simmer hard for 10 minutes, then reduce the heat. Nestle in the squid, then the shrimp and mussels and scatter the peas. Cook until the liquid is absorbed and the mussels have opened.', 1200, 'Medium then low heat', 'Rotate the pan on the burner so it cooks evenly.'],
      ['Socarrat', 'Turn the heat up for the last 90 seconds to crisp the bottom layer — you will hear it crackle. Rest 5 minutes under a towel. Lemon and parsley to serve.', 90, 'High heat'],
    ],
    subs: [['seafood', 'chicken thigh and chorizo, browned first'], ['saffron', '1/2 tsp turmeric', 'for colour, not the same flavour']],
    n: [560, 36, 70, 14],
    caption: 'Paella. Stirring is the enemy. Listen for the crackle.',
    daysAgo: 9,
  },
  {
    emoji: '🍛',
    title: 'Thai green curry with vegetables and tofu',
    summary: 'Coconut green curry loaded with eggplant, green beans, peppers and crispy tofu. Fragrant, fast and completely plant-based.',
    cuisine: 'Thai',
    meal: 'dinner',
    serves: 4,
    total: 30,
    active: 25,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['curry', 'weeknight', 'coconut'],
    allergens: ['soy'],
    equipment: ['wok or large pan'],
    techniques: ['frying paste', 'simmering'],
    ing: ['2 tbsp vegetable oil', '300 g tofu, firm, cubed', '3 tbsp curry paste, green', '400 ml coconut milk', '200 ml stock', '1 tbsp tamari', '1 tbsp brown sugar', '1 eggplant, cubed', '150 g green beans, trimmed', '1 bell pepper, sliced', '1 lime, juiced', '1 bunch basil', '?1 chili, sliced', 'rice, to serve'],
    steps: [
      ['Crisp the tofu', 'Fry the tofu in 1 tablespoon of oil until golden on a couple of sides. Set aside.', 360, 'Medium-high heat'],
      ['Fry the paste', 'Cook the curry paste in the remaining oil for a minute until it smells sharp and fragrant. Pour in a third of the coconut milk and stir until the oil starts to separate at the edges.', 180, 'Medium heat', 'Check the paste label — some contain shrimp.'],
      ['Simmer', 'Add the rest of the coconut milk, stock, tamari and sugar. Add the eggplant and simmer 8 minutes, then the beans and pepper for 4 more, until just tender.', 720],
      ['Finish', 'Return the tofu, add lime juice and most of the basil. Taste for salt, sweet and sour. Top with the remaining basil and chili, serve with rice.'],
    ],
    subs: [['tofu', 'chicken thigh, added with the eggplant'], ['eggplant', 'zucchini or bamboo shoots']],
    n: [450, 18, 26, 32],
    caption: 'Green curry from a jar of paste, elevated. Fry the paste properly.',
    daysAgo: 8,
  },
  {
    emoji: '🍗',
    title: 'Kung pao chicken',
    summary: 'Diced chicken with peanuts, dried chilies and a sticky, tangy Sichuan-style sauce. Twenty minutes, one wok, very hot.',
    cuisine: 'Chinese',
    meal: 'dinner',
    serves: 3,
    total: 25,
    active: 25,
    level: 'medium',
    diet: ['dairy-free', 'high-protein'],
    tags: ['stir-fry', 'spicy', 'weeknight'],
    allergens: ['peanuts', 'soy', 'gluten'],
    equipment: ['wok'],
    techniques: ['velveting', 'stir-frying'],
    ing: ['500 g chicken breast, diced', 'Velvet: 1 tbsp soy sauce', 'Velvet: 1 tbsp cornstarch', 'Velvet: 1 tsp vegetable oil', 'Sauce: 2 tbsp soy sauce', 'Sauce: 1 tbsp rice vinegar', 'Sauce: 1 tbsp sugar', 'Sauce: 1 tsp cornstarch', 'Sauce: 3 tbsp water', '2 tbsp vegetable oil', '8 chili, dried', '1 tsp black pepper, or Sichuan pepper', '3 cloves garlic, sliced', '1 thumb ginger, sliced', '4 spring onions, cut into lengths', '80 g peanuts, roasted', 'rice, to serve'],
    steps: [
      ['Velvet the chicken', 'Toss the chicken with the soy sauce, cornstarch and oil. Leave 10 minutes. Mix the sauce ingredients in a small bowl.', 600, null, 'Velveting is what keeps stir-fried chicken tender.'],
      ['Sear', 'Heat the oil in a wok until smoking. Add the chicken in a single layer and leave it for a minute before tossing. Cook until just done and remove.', 240, 'Very high heat'],
      ['Aromatics', 'Add the dried chilies and pepper to the wok for 20 seconds, then the garlic, ginger and spring onions for 30 more.', 60, 'High heat'],
      ['Sauce and toss', 'Return the chicken, pour in the sauce and toss until it thickens and clings. Add the peanuts, toss once more, and serve with rice.', 60],
    ],
    subs: [['peanuts', 'cashews', 'still tree nuts'], ['soy sauce', 'tamari', 'gluten-free']],
    n: [470, 42, 20, 24],
    caption: 'Kung pao. Get the wok hotter than you think is sensible.',
    daysAgo: 7,
  },
  {
    emoji: '🥩',
    title: 'Slow-braised brisket with onions',
    summary: 'A whole brisket braised for hours with a mountain of onions until it slices like butter. Kosher-style, no dairy, no fuss.',
    cuisine: 'Jewish',
    meal: 'dinner',
    serves: 8,
    total: 260,
    active: 30,
    level: 'medium',
    diet: ['kosher', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['braise', 'holiday', 'make-ahead', 'big-batch'],
    equipment: ['dutch oven or roasting pan with lid'],
    techniques: ['searing', 'braising'],
    ing: ['1.8 kg beef stew, brisket in one piece', 'salt', 'black pepper', '2 tbsp vegetable oil', '4 onions, thickly sliced', '4 cloves garlic, crushed', '2 tbsp tomato paste', '2 tbsp paprika', '500 ml stock', '2 tbsp brown sugar', '2 tbsp vinegar', '3 carrot, cut into chunks', '2 bay leaf'],
    steps: [
      ['Sear', 'Season the brisket heavily. Sear in the oil in a dutch oven until deeply browned on both sides. Remove.', 600, 'High heat'],
      ['Onions', 'Add the onions and cook until golden and softened, then the garlic, tomato paste and paprika for 2 minutes.', 900, 'Medium heat'],
      ['Braise', 'Stir in the stock, sugar and vinegar. Return the brisket, add the carrots and bay leaves, cover tightly, and braise in the oven until a fork slides in with no resistance.', 12600, 'Oven 160°C / 325°F', 'Fat cap up. Check at 3 hours; it may want 4.'],
      ['Rest and slice', 'Rest the brisket 20 minutes (or chill overnight — it slices cleaner cold). Slice across the grain and return to the sauce to warm.', 1200],
    ],
    subs: [['brisket', 'beef chuck', 'shorter braise, similar result']],
    makeAhead: 'Made the day before, chilled, sliced cold and reheated in its sauce, it is at its best.',
    n: [540, 48, 16, 30],
    caption: 'Holiday brisket. Slice it cold the next day and reheat in the sauce.',
    daysAgo: 6,
  },
  {
    emoji: '🐠',
    title: 'Baked cod with tomatoes, olives and capers',
    summary: 'Cod fillets baked over a quick tomato, olive and caper sauce. Fifteen minutes in the oven, no carbs to speak of.',
    cuisine: 'Mediterranean',
    meal: 'dinner',
    serves: 2,
    total: 25,
    active: 10,
    level: 'easy',
    diet: ['pescatarian', 'gluten-free', 'dairy-free', 'nut-free', 'keto-friendly', 'low-carb', 'high-protein'],
    tags: ['quick', 'bake', 'light', 'weeknight'],
    equipment: ['baking dish'],
    techniques: ['baking'],
    ing: ['2 fillets cod', 'salt', 'black pepper', '2 tbsp olive oil', '250 g cherry tomatoes, halved', '60 g olives, halved', '1 tbsp capers', '2 cloves garlic, sliced', '1 tsp oregano', '1/2 lemon, juiced', '1 handful parsley'],
    steps: [
      ['Build the sauce', 'Toss the tomatoes, olives, capers, garlic, oregano and 1 tablespoon of oil in a baking dish with salt and pepper. Roast 8 minutes until the tomatoes start to burst.', 480, 'Oven 200°C / 400°F'],
      ['Add the fish', 'Season the cod, set it on top of the tomatoes, drizzle with the remaining oil and lemon juice. Bake until the fish flakes when pressed.', 720, 'Oven 200°C / 400°F', 'Thick fillets take 12 minutes; thin ones 9.'],
      ['Serve', 'Scatter parsley and spoon the pan juices over. Crusty bread or greens alongside.'],
    ],
    subs: [['cod', 'any firm white fish, or chicken breast (bake 22 minutes)']],
    n: [330, 34, 10, 18],
    caption: 'Cod in fifteen minutes. The tomatoes make their own sauce.',
    daysAgo: 5,
  },
  {
    emoji: '🍜',
    title: 'Quick chicken pho',
    summary: 'A weeknight pho: stock deepened with charred ginger, onion and spices, poured over rice noodles, chicken and a pile of herbs.',
    cuisine: 'Vietnamese',
    meal: 'dinner',
    serves: 4,
    total: 45,
    active: 20,
    level: 'medium',
    diet: ['gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['soup', 'noodles', 'aromatic'],
    equipment: ['large pot'],
    techniques: ['charring', 'simmering'],
    ing: ['1 onion, halved', '1 thumb ginger, halved lengthwise', '2 l stock', '2 chicken breast', '2 star anise', '1 cinnamon stick', '3 cloves', '1 tsp coriander seed', '2 tbsp fish sauce', '1 tsp sugar', '300 g rice noodles', '2 spring onions, sliced', '1 bunch cilantro', '1 bunch mint', '100 g bean sprouts', '1 lime, cut into wedges', '?1 chili, sliced', '?hoisin and hot sauce'],
    steps: [
      ['Char the aromatics', 'Char the onion and ginger cut-side down in a dry pot (or under the grill) until blackened in spots.', 300, 'High heat', 'The char is what makes stock taste like pho.'],
      ['Simmer the broth', 'Add the stock, chicken breasts, star anise, cinnamon, cloves and coriander seed. Simmer gently 20 minutes; remove the chicken once cooked through and shred it. Strain the broth and season with fish sauce and sugar.', 1200, 'Low heat'],
      ['Noodles', 'Soak or boil the rice noodles per the packet, drain, and divide between four bowls with the shredded chicken.', 300],
      ['Assemble', 'Pour the very hot broth over. Everyone adds spring onions, herbs, sprouts, lime, chili and sauces to taste.'],
    ],
    subs: [['chicken', 'firm tofu and mushroom stock', 'vegetarian; use tamari for the fish sauce']],
    n: [420, 30, 58, 6],
    caption: 'Pho on a Wednesday. Char the ginger and onion — that is 80% of it.',
    daysAgo: 4,
  },
  {
    emoji: '🥦',
    title: 'Beef and broccoli stir-fry',
    summary: 'Tender velveted beef and crisp broccoli in a glossy garlic-ginger sauce. Faster than the delivery app.',
    cuisine: 'Chinese-American',
    meal: 'dinner',
    serves: 3,
    total: 25,
    active: 25,
    level: 'easy',
    diet: ['dairy-free', 'nut-free', 'high-protein'],
    tags: ['stir-fry', 'weeknight', 'takeaway-at-home'],
    allergens: ['soy', 'gluten'],
    equipment: ['wok'],
    techniques: ['velveting', 'stir-frying', 'blanching'],
    ing: ['450 g beef steak, thinly sliced', 'Velvet: 1 tbsp soy sauce', 'Velvet: 1 tbsp cornstarch', 'Velvet: 1/2 tsp baking soda', '400 g broccoli, cut into florets', 'Sauce: 3 tbsp soy sauce', 'Sauce: 2 tbsp oyster sauce', 'Sauce: 1 tbsp brown sugar', 'Sauce: 1 tsp cornstarch', 'Sauce: 100 ml stock', '2 tbsp vegetable oil', '3 cloves garlic, minced', '1 thumb ginger, minced', 'rice, to serve'],
    steps: [
      ['Velvet', 'Toss the beef with the soy sauce, cornstarch and baking soda. Rest 15 minutes. Whisk the sauce ingredients together.', 900, null, 'The pinch of baking soda is the takeaway secret to tender beef.'],
      ['Blanch the broccoli', 'Drop the broccoli into boiling water for 90 seconds, then drain.', 90],
      ['Sear the beef', 'Heat the oil in a wok until smoking. Sear the beef in a single layer without moving it for a minute, then toss until browned. Remove.', 180, 'Very high heat'],
      ['Sauce', 'Fry the garlic and ginger for 20 seconds, add the sauce and let it bubble and thicken. Return the beef and broccoli and toss to coat. Serve over rice.', 120],
    ],
    subs: [['oyster sauce', 'hoisin or more soy with a pinch of sugar'], ['beef', 'mushrooms and tofu']],
    n: [490, 40, 24, 24],
    caption: 'Beef and broccoli in the time it takes to boil rice.',
    daysAgo: 3,
  },
  {
    emoji: '🍝',
    title: 'Lentil bolognese',
    summary: 'Brown lentils cooked low with tomatoes, wine and a proper soffritto until it eats like a meat sauce. Huge batch, freezes beautifully.',
    cuisine: 'Italian',
    meal: 'dinner',
    serves: 6,
    total: 70,
    active: 25,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['big-batch', 'freezer-friendly', 'comfort', 'budget'],
    equipment: ['large pot'],
    techniques: ['soffritto', 'simmering'],
    ing: ['3 tbsp olive oil', '1 onion, finely diced', '2 carrot, finely diced', '2 celery, finely diced', '4 cloves garlic, minced', '2 tbsp tomato paste', '150 ml red wine', '300 g lentils, brown or green', '800 g canned tomatoes', '500 ml stock', '2 bay leaf', '1 tsp oregano', 'salt', 'black pepper', '500 g pasta, to serve', '?1 tsp soy sauce, for depth'],
    steps: [
      ['Soffritto', 'Cook the onion, carrot and celery in the oil with a pinch of salt over medium-low heat until very soft and sweet. Do not rush it.', 900, 'Medium-low heat'],
      ['Deepen', 'Add the garlic and tomato paste and cook 2 minutes. Pour in the wine and let it reduce by half.', 240, 'Medium heat'],
      ['Simmer', 'Add the lentils, tomatoes, stock, bay leaves and oregano. Simmer, partly covered, until the lentils are tender and the sauce is thick and dark. Season well with salt, pepper and the soy sauce.', 2400, 'Low heat', 'If it thickens too fast, add stock; lentils drink a lot.'],
      ['Serve', 'Toss with cooked pasta and a little of its water so the sauce clings.'],
    ],
    subs: [['red wine', 'more stock + 1 tsp balsamic'], ['pasta', 'gluten-free pasta or polenta']],
    storage: 'Sauce keeps 5 days; freezes 3 months.',
    n: [520, 22, 84, 10],
    caption: 'Lentil bolognese: the pot we make on Sunday for the whole week.',
    daysAgo: 2,
  },
  {
    emoji: '🥩',
    title: 'Lamb kofta with tzatziki',
    summary: 'Spiced ground lamb shaped onto skewers and grilled, with a garlicky cucumber-yogurt sauce and warm flatbread.',
    cuisine: 'Greek',
    meal: 'dinner',
    serves: 4,
    total: 35,
    active: 30,
    level: 'easy',
    diet: ['gluten-free', 'nut-free', 'halal', 'high-protein', 'low-carb'],
    tags: ['grill', 'skewers', 'summer'],
    equipment: ['grill pan or barbecue', 'skewers'],
    techniques: ['grilling'],
    ing: ['Kofta: 600 g lamb, ground', 'Kofta: 1 onion, grated and squeezed dry', 'Kofta: 3 cloves garlic, minced', 'Kofta: 2 tsp cumin', 'Kofta: 1 tsp coriander seed, ground', 'Kofta: 1 tsp paprika', 'Kofta: 1/2 tsp cinnamon', 'Kofta: 1 handful parsley, chopped', 'Kofta: 1 tsp salt', 'Tzatziki: 250 g yogurt', 'Tzatziki: 1/2 cucumber, grated and squeezed', 'Tzatziki: 1 clove garlic, minced', 'Tzatziki: 1 tbsp olive oil', 'Tzatziki: 1 tbsp mint, chopped', 'Tzatziki: 1/2 lemon, juiced', '1 tbsp olive oil', '?pita or flatbread', '?tomato and cucumber salad'],
    steps: [
      ['Mix the kofta', 'Combine the lamb, squeezed onion, garlic, spices, parsley and salt. Knead a minute until sticky — this helps them hold. Chill 15 minutes.', 900, null, 'Squeezing the onion dry stops the kofta falling apart.'],
      ['Tzatziki', 'Mix the yogurt, squeezed cucumber, garlic, olive oil, mint and lemon. Salt to taste.'],
      ['Shape and grill', 'Shape the meat into 8 sausage shapes around skewers (or freeform). Brush with oil and grill over high heat, turning, until charred outside and just cooked through.', 600, 'High heat'],
      ['Serve', 'With tzatziki, warm flatbread and a chopped salad.'],
    ],
    subs: [['lamb', 'ground beef or turkey'], ['yogurt', 'coconut yogurt', 'dairy-free']],
    n: [520, 38, 8, 36],
    caption: 'Kofta night. Squeeze the onion, chill the mix, grill hot.',
    daysAgo: 1,
  },
  {
    emoji: '🥬',
    title: 'Cauliflower steaks with chimichurri',
    summary: 'Thick slabs of cauliflower roasted until caramelized, with a punchy herb, garlic and vinegar chimichurri. A vegan main that feels like a steak.',
    cuisine: 'Argentinian',
    meal: 'dinner',
    serves: 2,
    total: 40,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'keto-friendly', 'low-carb'],
    tags: ['roast', 'plant-based', 'sauce'],
    equipment: ['baking tray'],
    techniques: ['roasting'],
    ing: ['1 head cauliflower, cut into 2 thick steaks plus florets', '3 tbsp olive oil', '1 tsp paprika', 'salt', 'black pepper', 'Chimichurri: 1 bunch parsley, finely chopped', 'Chimichurri: 2 tbsp oregano, fresh, or 1 tsp dried', 'Chimichurri: 3 cloves garlic, minced', 'Chimichurri: 1/2 tsp chili flakes', 'Chimichurri: 3 tbsp vinegar, red wine', 'Chimichurri: 100 ml olive oil', '?white beans, warmed, to serve'],
    steps: [
      ['Roast', 'Brush the cauliflower steaks and florets with oil, season with paprika, salt and pepper. Roast on a hot tray, flipping once, until deeply browned and tender when pierced.', 1800, 'Oven 220°C / 425°F', 'Preheat the tray so the first side sears on contact.'],
      ['Chimichurri', 'Stir together the parsley, oregano, garlic, chili flakes, vinegar and olive oil with a big pinch of salt. Let it sit while the cauliflower roasts.', 600],
      ['Serve', 'Spoon the chimichurri generously over the steaks. Warm white beans alongside make it a full plate.'],
    ],
    subs: [['cauliflower', 'thick cabbage wedges', 'roast the same way']],
    n: [380, 8, 18, 32],
    caption: 'Cauliflower steak with chimichurri. Make double the sauce; it goes on everything.',
    daysAgo: 23,
  },
  {
    emoji: '🍛',
    title: 'Chana masala',
    summary: 'Chickpeas in a tangy, deeply spiced tomato-onion gravy with ginger and a hit of lemon. Pantry dinner, restaurant flavour.',
    cuisine: 'Indian',
    meal: 'dinner',
    serves: 4,
    total: 35,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['curry', 'pantry', 'budget', 'weeknight'],
    equipment: ['pot'],
    techniques: ['tempering spices', 'simmering'],
    ing: ['2 tbsp vegetable oil', '1 tsp cumin, whole seeds', '1 onion, finely diced', '4 cloves garlic, minced', '1 thumb ginger, grated', '1 chili, minced', '2 tsp coriander seed, ground', '1 tsp turmeric', '1 tsp paprika', '1/2 tsp cinnamon', '400 g canned tomatoes', '2 cans chickpeas, drained', '200 ml water', 'salt', '1/2 lemon, juiced', '1 bunch cilantro', '?rice or naan'],
    steps: [
      ['Temper', 'Heat the oil and sizzle the cumin seeds for 20 seconds. Add the onion and cook until golden.', 480, 'Medium heat'],
      ['Aromatics and spices', 'Add the garlic, ginger and chili for a minute, then the ground coriander, turmeric, paprika and cinnamon. Stir 30 seconds, then add the tomatoes and cook until the oil separates at the edges.', 480, null, 'That separated oil means the masala is ready.'],
      ['Simmer', 'Add the chickpeas and water. Simmer, mashing a few chickpeas to thicken, until the sauce clings.', 720, 'Low heat'],
      ['Finish', 'Salt well, add lemon juice and cilantro. Serve with rice or naan.'],
    ],
    subs: [['canned chickpeas', '250 g dried, soaked and cooked']],
    storage: '4 days in the fridge; freezes well.',
    n: [360, 15, 52, 10],
    caption: 'Chana masala from two cans of chickpeas. Wait for the oil to separate.',
    daysAgo: 24,
  },
  {
    emoji: '🍖',
    title: 'Turkey meatballs with zucchini noodles',
    summary: 'Juicy baked turkey meatballs on a quick tomato sauce with spiralized zucchini. Light, high-protein, weeknight-fast.',
    cuisine: 'Italian-American',
    meal: 'dinner',
    serves: 4,
    total: 35,
    active: 25,
    level: 'easy',
    diet: ['gluten-free', 'dairy-free', 'nut-free', 'low-carb', 'high-protein'],
    tags: ['bake', 'light', 'meal-prep'],
    equipment: ['baking tray', 'skillet', 'spiralizer or peeler'],
    techniques: ['baking', 'sautéing'],
    ing: ['Meatballs: 600 g ground turkey', 'Meatballs: 1 egg', 'Meatballs: 3 tbsp almond flour', 'Meatballs: 2 cloves garlic, minced', 'Meatballs: 1 tsp oregano', 'Meatballs: 1 handful parsley, chopped', 'Meatballs: 1 tsp salt', 'Sauce: 1 tbsp olive oil', 'Sauce: 2 cloves garlic, sliced', 'Sauce: 400 g canned tomatoes', 'Sauce: 1/2 tsp chili flakes', '4 zucchini, spiralized', '1 tbsp olive oil', 'salt', '?parmesan'],
    steps: [
      ['Roll and bake', 'Mix the turkey, egg, almond flour, garlic, oregano, parsley and salt. Roll into 16 balls and bake on an oiled tray until browned and cooked through.', 1080, 'Oven 200°C / 400°F', 'Wet hands stop the mix sticking.'],
      ['Sauce', 'Meanwhile sizzle the garlic in the oil, add the tomatoes and chili flakes, and simmer until thickened. Season.', 600, 'Medium heat'],
      ['Zucchini noodles', 'In a hot skillet with the oil, toss the zucchini noodles for 2 minutes only — just warmed, still crisp. Salt lightly.', 120, 'High heat', 'Any longer and they weep and go soft.'],
      ['Serve', 'Noodles, sauce, meatballs, parmesan if you like.'],
    ],
    subs: [['almond flour', 'gluten-free breadcrumbs or oat flour', 'nut-free'], ['zucchini', 'spaghetti', 'if carbs are welcome']],
    n: [380, 40, 14, 18],
    caption: 'Turkey meatballs, zoodles, done in 35. Two minutes max on the zucchini.',
    daysAgo: 25,
  },
  {
    emoji: '🍛',
    title: 'Chicken katsu curry',
    summary: 'Crisp panko-breaded chicken over rice with a mild, glossy Japanese curry sauce. A weekend project that is worth every step.',
    cuisine: 'Japanese',
    meal: 'dinner',
    serves: 4,
    total: 60,
    active: 45,
    level: 'medium',
    diet: ['dairy-free', 'nut-free', 'high-protein'],
    tags: ['fried', 'comfort', 'weekend'],
    allergens: ['gluten', 'eggs', 'soy'],
    equipment: ['skillet', 'pot'],
    techniques: ['breading', 'shallow frying', 'roux'],
    ing: ['Sauce: 2 tbsp vegetable oil', 'Sauce: 1 onion, diced', 'Sauce: 1 carrot, diced', 'Sauce: 1 potato, diced', 'Sauce: 2 cloves garlic, minced', 'Sauce: 2 tbsp flour', 'Sauce: 2 tbsp curry powder', 'Sauce: 600 ml stock', 'Sauce: 1 tbsp soy sauce', 'Sauce: 1 tbsp honey', 'Sauce: 1 apple, grated', 'Katsu: 4 chicken breast, flattened to 1.5 cm', 'Katsu: 50 g flour', 'Katsu: 2 eggs, beaten', 'Katsu: 120 g breadcrumbs, panko', 'Katsu: 200 ml vegetable oil, for frying', 'salt', '300 g rice, cooked', '?pickled ginger'],
    steps: [
      ['Curry sauce', 'Soften the onion, carrot and potato in the oil. Add the garlic, then the flour and curry powder and stir a minute to make a roux. Gradually whisk in the stock, then add the soy sauce, honey and grated apple. Simmer until the vegetables are tender and the sauce is thick.', 1500, 'Medium-low heat'],
      ['Bread the chicken', 'Season the chicken. Dredge in flour, dip in egg, then press into panko so it is fully coated.'],
      ['Fry', 'Shallow-fry in 1 cm of oil until deep golden on both sides and cooked through. Drain on a rack and salt lightly.', 480, 'Oil at 170°C / 340°F', 'A rack, not paper, keeps the crust crisp.'],
      ['Plate', 'Slice the katsu into strips, lay over rice, and pour the curry alongside (not over the crust). Pickled ginger on the side.'],
    ],
    subs: [['chicken', 'firm tofu or eggplant slices'], ['panko + flour', 'gluten-free panko and rice flour']],
    n: [760, 46, 74, 30],
    caption: 'Katsu curry. Sauce beside the cutlet, never over it — protect the crunch.',
    daysAgo: 26,
  },
  // ---------------------------------------------------------------- sides
  {
    emoji: '🥦',
    title: 'Garlic roasted broccoli with lemon',
    summary: 'Broccoli roasted hot until the edges crisp and char, tossed with garlic and lemon. The side that disappears first.',
    cuisine: 'American',
    meal: 'side',
    serves: 4,
    total: 25,
    active: 5,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'keto-friendly', 'low-carb'],
    tags: ['roast', 'quick', 'vegetable'],
    equipment: ['baking tray'],
    techniques: ['roasting'],
    ing: ['2 heads broccoli, cut into florets', '3 tbsp olive oil', '3 cloves garlic, thinly sliced', 'salt', 'black pepper', '1/2 lemon', '?chili flakes', '?parmesan'],
    steps: [
      ['Toss', 'Toss the broccoli with the oil, salt and pepper and spread out on a tray — crowding steams it.'],
      ['Roast', 'Roast until the tips are crisp and browned, adding the garlic for the last 5 minutes so it turns golden, not black.', 1200, 'Oven 220°C / 425°F'],
      ['Finish', 'Squeeze over the lemon, add chili flakes or parmesan, and serve hot.'],
    ],
    n: [140, 5, 10, 11],
    caption: 'The only way we cook broccoli now.',
    daysAgo: 27,
  },
  {
    emoji: '🌽',
    title: 'Mexican street corn salad (esquites)',
    summary: 'Charred corn with lime, chili, cotija-style cheese and a little mayo — elote in a bowl, no cob required.',
    cuisine: 'Mexican',
    meal: 'side',
    serves: 4,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['summer', 'bbq', 'quick'],
    allergens: ['eggs'],
    equipment: ['skillet'],
    techniques: ['charring'],
    ing: ['1 tbsp vegetable oil', '500 g corn', '2 tbsp mayonnaise', '1 lime, juiced', '1/2 tsp chili powder', '60 g feta, crumbled', '2 spring onions, sliced', '1 handful cilantro, chopped', 'salt'],
    steps: [
      ['Char', 'Heat the oil in a skillet until smoking. Add the corn and leave it alone until blackened in spots, then toss and char the other side.', 360, 'High heat'],
      ['Dress', 'Off the heat, stir in the mayonnaise, lime juice and chili powder. Fold in the feta, spring onions and cilantro. Salt to taste.'],
    ],
    subs: [['mayonnaise', 'Greek yogurt or vegan mayo'], ['feta', 'cotija, if you can get it']],
    n: [220, 6, 24, 12],
    caption: 'Esquites: elote you can eat with a fork.',
    daysAgo: 28,
  },
  {
    emoji: '🌿',
    title: 'Tabbouleh',
    summary: 'Mostly parsley, a little bulgur: the real proportions. Tomatoes, mint, lemon and good olive oil.',
    cuisine: 'Lebanese',
    meal: 'side',
    serves: 4,
    total: 25,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'dairy-free', 'nut-free'],
    tags: ['fresh', 'herbs', 'no-cook'],
    allergens: ['gluten'],
    equipment: ['bowl'],
    techniques: ['soaking', 'fine chopping'],
    ing: ['50 g bulgur, fine', '3 bunches parsley, finely chopped', '1 bunch mint, finely chopped', '3 tomatoes, finely diced', '4 spring onions, finely sliced', '1 lemon, juiced', '4 tbsp olive oil', 'salt', '?1/2 tsp allspice'],
    steps: [
      ['Soak the bulgur', 'Cover the bulgur with just-boiled water and leave 10 minutes, then drain and squeeze dry.', 600],
      ['Chop', 'Chop the parsley and mint as finely as you have patience for. Dice the tomatoes small and drain off their juice.'],
      ['Toss', 'Combine everything with the lemon juice, olive oil and salt. Taste — it should be bright and lemony. Eat within the hour.'],
    ],
    subs: [['bulgur', 'quinoa, cooked', 'gluten-free']],
    n: [180, 3, 14, 14],
    caption: 'Tabbouleh is a parsley salad with bulgur in it, not the other way round.',
    daysAgo: 29,
  },
  {
    emoji: '🥔',
    title: 'Crispy smashed potatoes',
    summary: 'Boiled baby potatoes flattened and roasted until shattering-crisp, with rosemary and garlic. Better than fries.',
    cuisine: 'British',
    meal: 'side',
    serves: 4,
    total: 55,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['roast', 'crispy', 'crowd-pleaser'],
    equipment: ['pot', 'baking tray'],
    techniques: ['boiling', 'roasting'],
    ing: ['1 kg potato, small', 'salt', '4 tbsp olive oil', '2 sprigs rosemary, chopped', '3 cloves garlic, minced', 'black pepper', '?flaky salt'],
    steps: [
      ['Boil', 'Boil the potatoes in well-salted water until completely tender. Drain and let them steam dry for a few minutes.', 1200],
      ['Smash', 'Spread on an oiled tray and press each one flat with the bottom of a glass. Drizzle with the rest of the oil, scatter rosemary, salt and pepper.', null, null, 'Crags and cracks are where the crunch lives.'],
      ['Roast', 'Roast until golden and crisp, adding the garlic for the last 5 minutes. Finish with flaky salt.', 1800, 'Oven 220°C / 425°F'],
    ],
    n: [260, 5, 40, 10],
    caption: 'Smashed potatoes. Boil, squash, roast. That is it.',
    daysAgo: 30,
  },
  // ---------------------------------------------------------------- snacks
  {
    emoji: '🫙',
    title: 'Silky hummus',
    summary: 'The trick is overcooking the chickpeas and blending with ice-cold water. Smooth, tahini-forward, restaurant hummus.',
    cuisine: 'Levantine',
    meal: 'snack',
    serves: 6,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['dip', 'meal-prep', 'pantry'],
    allergens: ['sesame'],
    equipment: ['food processor'],
    techniques: ['blending'],
    ing: ['2 cans chickpeas', '1/2 tsp baking soda', '120 g tahini', '1 lemon, juiced', '2 cloves garlic', '1 tsp cumin', '1 tsp salt', '4 tbsp water, iced', '2 tbsp olive oil', '?paprika'],
    steps: [
      ['Soften the chickpeas', 'Simmer the chickpeas with their liquid and the baking soda for 10 minutes until very soft and the skins slip. Drain.', 600, 'Medium heat', 'This is the step everyone skips and the reason theirs is grainy.'],
      ['Blend', 'Blend the tahini, lemon juice, garlic, cumin and salt first until whipped. Add the chickpeas and blend, streaming in iced water, for a full 3 minutes until completely smooth.', 180],
      ['Serve', 'Swirl onto a plate, drizzle with olive oil and dust with paprika.'],
    ],
    storage: '5 days in the fridge.',
    n: [210, 8, 18, 12],
    caption: 'Hummus, but smooth. Ten extra minutes of simmering changes everything.',
    daysAgo: 31,
  },
  {
    emoji: '🥑',
    title: 'Guacamole',
    summary: 'Avocado, lime, onion, chili, cilantro, salt. Chunky, bright, gone in five minutes.',
    cuisine: 'Mexican',
    meal: 'snack',
    serves: 4,
    total: 10,
    active: 10,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'keto-friendly', 'low-carb'],
    tags: ['dip', 'no-cook', 'quick'],
    equipment: ['bowl'],
    techniques: ['mashing'],
    ing: ['3 avocado', '1 lime, juiced', '1/2 red onion, finely diced', '1 chili, minced', '1 handful cilantro, chopped', '1/2 tsp salt', '?1 tomato, diced'],
    steps: [
      ['Mash', 'Halve and scoop the avocados. Mash roughly with the lime juice and salt, leaving plenty of chunks.'],
      ['Fold', 'Stir through the onion, chili, cilantro and tomato. Taste for salt and lime. Serve right away.'],
    ],
    n: [190, 2, 12, 16],
    caption: 'Guac. Under-mash it.',
    daysAgo: 32,
  },
  {
    emoji: '🫘',
    title: 'Crunchy roasted chickpeas',
    summary: 'Chickpeas roasted until they rattle on the tray, tossed in smoked paprika and cumin. A snack, a salad topper, a crouton replacement.',
    cuisine: 'Mediterranean',
    meal: 'snack',
    serves: 4,
    total: 45,
    active: 5,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'],
    tags: ['crunchy', 'pantry', 'meal-prep'],
    equipment: ['baking tray'],
    techniques: ['roasting'],
    ing: ['2 cans chickpeas, drained and patted very dry', '2 tbsp olive oil', '1 tsp paprika', '1 tsp cumin', '1/2 tsp salt', '?1/4 tsp cayenne'],
    steps: [
      ['Dry them', 'Rub the chickpeas dry in a clean towel — the drier they are, the crunchier they get.'],
      ['Roast plain', 'Toss with the oil only and roast, shaking the tray twice, until golden and crunchy.', 2100, 'Oven 200°C / 400°F', 'Spices go on after so they do not scorch.'],
      ['Season', 'Toss the hot chickpeas with paprika, cumin, salt and cayenne. Cool on the tray; they crisp further.'],
    ],
    storage: 'Airtight at room temperature, 3 days.',
    n: [190, 9, 24, 7],
    caption: 'Roasted chickpeas that stay crunchy: dry them properly, spice them after.',
    daysAgo: 33,
  },
  {
    emoji: '🍪',
    title: 'No-bake seed and date energy bites',
    summary: 'Dates, oats, sunflower and pumpkin seeds, cocoa and a pinch of salt, rolled into bites. Nut-free, lunchbox-safe, no oven.',
    cuisine: 'American',
    meal: 'snack',
    serves: 12,
    total: 20,
    active: 20,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['no-bake', 'kid-friendly', 'meal-prep'],
    equipment: ['food processor'],
    techniques: ['blending', 'rolling'],
    ing: ['200 g dates, pitted', '100 g oats', '60 g sunflower seeds', '40 g pumpkin seeds', '2 tbsp cocoa', '1 tbsp chia seeds', 'pinch salt', '1 tsp vanilla', '?2 tbsp water'],
    steps: [
      ['Blend', 'Blend the dates until they form a paste. Add the oats, seeds, cocoa, chia, salt and vanilla and pulse until the mix clumps when pressed. Add a splash of water if it is too dry.'],
      ['Roll', 'Roll into 12 balls with damp hands. Chill 30 minutes to firm up.', 1800],
    ],
    storage: 'Fridge for 2 weeks, freezer for 3 months.',
    n: [130, 3, 20, 5],
    caption: 'Energy bites without nuts, so they can go to school.',
    daysAgo: 34,
  },
  // ---------------------------------------------------------------- desserts
  {
    emoji: '🍫',
    title: 'Flourless chocolate cake',
    summary: 'Dark chocolate, butter, eggs and sugar — dense, fudgy, naturally gluten-free. A dinner-party cake with five ingredients.',
    cuisine: 'French',
    meal: 'dessert',
    serves: 10,
    total: 60,
    active: 20,
    level: 'medium',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['bake', 'chocolate', 'celebration'],
    equipment: ['20 cm cake tin', 'mixer'],
    techniques: ['melting', 'whipping', 'baking'],
    ing: ['250 g dark chocolate, chopped', '200 g butter', '5 eggs, separated', '150 g sugar', 'pinch salt', '1 tsp vanilla', '?cocoa, for dusting', '?berries, to serve'],
    steps: [
      ['Melt', 'Line a 20 cm tin. Melt the chocolate and butter together gently, then let it cool for 5 minutes.', 300, 'Low heat or microwave in bursts'],
      ['Yolks', 'Whisk the yolks with half the sugar, the salt and vanilla until pale. Stir into the chocolate.'],
      ['Whites', 'Whip the whites to soft peaks, add the remaining sugar and whip to firm, glossy peaks. Fold a third into the chocolate to loosen it, then fold in the rest gently.', null, null, 'Streaks of white are fine; overmixing deflates it.'],
      ['Bake', 'Pour into the tin and bake until the top is set and cracked and a skewer comes out with moist crumbs. It will sink as it cools — that is correct.', 1800, 'Oven 170°C / 340°F'],
      ['Serve', 'Cool completely. Dust with cocoa and serve with berries.'],
    ],
    subs: [['butter', 'coconut oil', 'dairy-free']],
    storage: 'Keeps 4 days, covered. Even better on day two.',
    n: [380, 6, 26, 28],
    caption: 'Five ingredients, no flour, no excuses. It is supposed to sink.',
    daysAgo: 35,
  },
  {
    emoji: '🥭',
    title: 'Mango sticky rice',
    summary: 'Glutinous rice steamed and soaked in sweet coconut cream, served with ripe mango and a salty-sweet drizzle.',
    cuisine: 'Thai',
    meal: 'dessert',
    serves: 4,
    total: 90,
    active: 25,
    level: 'medium',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['fruit', 'coconut', 'classic'],
    equipment: ['steamer', 'pot'],
    techniques: ['soaking', 'steaming'],
    ing: ['300 g rice, glutinous', '400 ml coconut milk', '80 g sugar', '1/2 tsp salt', '2 mango, ripe, sliced', '?1 tbsp sesame seeds, toasted'],
    steps: [
      ['Soak', 'Soak the rice in cold water for at least 1 hour, ideally 4. Drain.', 3600],
      ['Steam', 'Steam the rice in a cloth-lined steamer until translucent and tender.', 1500],
      ['Sweeten', 'Warm 300 ml of the coconut milk with the sugar and salt until dissolved (do not boil). Pour over the hot rice, stir, cover, and leave 20 minutes to absorb.', 1200, 'Low heat'],
      ['Serve', 'Mound the rice, fan the mango alongside, drizzle with the remaining coconut milk and a few sesame seeds.'],
    ],
    n: [520, 6, 96, 14],
    caption: 'Mango sticky rice. Worth the soak.',
    daysAgo: 36,
  },
  {
    emoji: '🍮',
    title: 'Vanilla chia pudding with roasted plums',
    summary: 'Chia set in coconut milk and vanilla, topped with plums roasted until jammy. Make it the night before; dessert or breakfast, your call.',
    cuisine: 'Modern',
    meal: 'dessert',
    serves: 4,
    total: 260,
    active: 15,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['make-ahead', 'light', 'fruit'],
    equipment: ['bowl', 'baking dish'],
    techniques: ['setting', 'roasting'],
    ing: ['60 g chia seeds', '400 ml coconut milk', '2 tbsp maple syrup', '1 tsp vanilla', 'pinch salt', '6 plums, halved and stoned', '1 tbsp brown sugar', '1/2 tsp cinnamon'],
    steps: [
      ['Set the pudding', 'Whisk the chia, coconut milk, maple syrup, vanilla and salt. Whisk again after 10 minutes to break up clumps, then chill at least 4 hours.', 14400],
      ['Roast the plums', 'Toss the plums with sugar and cinnamon and roast cut-side up until soft and bubbling.', 1200, 'Oven 200°C / 400°F'],
      ['Serve', 'Spoon the pudding into glasses and top with warm or cold plums and their juices.'],
    ],
    subs: [['plums', 'berries, apricots or pears']],
    n: [280, 5, 30, 16],
    caption: 'Chia pudding that does not taste like a health food, thanks to the roasted plums.',
    daysAgo: 37,
  },
  {
    emoji: '🍎',
    title: 'Apple and oat crumble',
    summary: 'Cinnamon apples under a buttery oat topping, gluten-free by default. Ready in under an hour, ice cream mandatory.',
    cuisine: 'British',
    meal: 'dessert',
    serves: 6,
    total: 55,
    active: 15,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['bake', 'comfort', 'autumn'],
    equipment: ['baking dish'],
    techniques: ['rubbing in', 'baking'],
    ing: ['6 apple, peeled and sliced', '2 tbsp sugar', '1 tsp cinnamon', '1 lemon, juiced', 'Topping: 120 g oats', 'Topping: 60 g gluten-free flour', 'Topping: 80 g brown sugar', 'Topping: 100 g butter, cold and cubed', 'Topping: pinch salt'],
    steps: [
      ['Fruit', 'Toss the apples with the sugar, cinnamon and lemon juice and tip into a baking dish.'],
      ['Topping', 'Rub the butter into the oats, flour, brown sugar and salt with your fingertips until clumpy. Scatter over the apples.', null, null, 'Squeeze some of the mix into bigger clumps for a craggy top.'],
      ['Bake', 'Bake until the top is golden and the fruit is bubbling at the edges. Rest 10 minutes before serving.', 2400, 'Oven 190°C / 375°F'],
    ],
    subs: [['butter', 'cold coconut oil', 'vegan'], ['apples', 'pears, or half apples half berries']],
    n: [390, 5, 60, 16],
    caption: 'Crumble. Gluten-free without trying, because oats.',
    daysAgo: 38,
  },
  {
    emoji: '🍰',
    title: 'Burnt Basque cheesecake',
    summary: 'A crustless cheesecake baked hot and fast so the top blackens while the centre stays custardy. Rustic on purpose.',
    cuisine: 'Spanish',
    meal: 'dessert',
    serves: 10,
    total: 70,
    active: 15,
    level: 'medium',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['bake', 'showpiece', 'easy-impressive'],
    equipment: ['20 cm springform tin', 'mixer'],
    techniques: ['baking'],
    ing: ['900 g cream cheese, room temperature', '250 g sugar', '5 eggs', '400 ml heavy cream', '1 tbsp cornstarch', '1 tsp vanilla', 'pinch salt'],
    steps: [
      ['Line the tin', 'Press two overlapping sheets of parchment into the tin so they stick up well above the rim — the crinkles are part of the look.', null, 'Oven 220°C / 425°F'],
      ['Mix', 'Beat the cream cheese and sugar until smooth. Add the eggs one at a time, then the cream, cornstarch, vanilla and salt. Mix only until smooth — no air.'],
      ['Bake hot', 'Pour into the tin and bake until the top is deeply browned, almost black in places, and the centre still wobbles like jelly when nudged.', 3000, 'Oven 220°C / 425°F', 'It will look underdone. It is not.'],
      ['Cool', 'Cool completely in the tin, then chill at least 4 hours. Serve in thick slices, at room temperature.', 14400],
    ],
    storage: '4 days in the fridge.',
    n: [520, 9, 30, 42],
    caption: 'Basque cheesecake: the one dessert where burning it is the recipe.',
    daysAgo: 39,
  },
  {
    emoji: '☕',
    title: 'Tiramisu',
    summary: 'Espresso-soaked ladyfingers layered with mascarpone cream and cocoa. No baking, but an overnight rest makes it.',
    cuisine: 'Italian',
    meal: 'dessert',
    serves: 8,
    total: 40,
    active: 40,
    level: 'medium',
    diet: ['vegetarian', 'nut-free'],
    tags: ['no-bake', 'make-ahead', 'classic'],
    allergens: ['gluten', 'eggs', 'dairy'],
    equipment: ['20 cm dish', 'mixer'],
    techniques: ['whipping', 'layering'],
    ing: ['300 ml espresso, strong, cooled', '2 tbsp sugar', '4 eggs, separated', '100 g sugar', '500 g mascarpone', '1 tsp vanilla', '250 g ladyfinger biscuits', '2 tbsp cocoa', '?2 tbsp coffee liqueur'],
    steps: [
      ['Coffee', 'Stir 2 tablespoons of sugar (and the liqueur) into the cooled espresso.'],
      ['Cream', 'Whisk the yolks with the 100 g sugar over a bain-marie until thick and pale, then cool. Beat in the mascarpone and vanilla. Whip the whites to soft peaks and fold in.', 600, null, 'Cooking the yolks gently over water makes the cream safe and stable.'],
      ['Layer', 'Dip each biscuit in coffee for one second per side — no longer — and line the dish. Spread half the cream. Repeat. Dust the top thickly with cocoa.'],
      ['Rest', 'Chill at least 6 hours, ideally overnight.', 21600],
    ],
    subs: [['ladyfingers', 'gluten-free sponge fingers']],
    n: [420, 9, 34, 28],
    caption: 'Tiramisu. One second per side in the coffee — count it.',
    daysAgo: 40,
  },
  // ---------------------------------------------------------------- drinks
  {
    emoji: '🫖',
    title: 'Masala chai',
    summary: 'Black tea simmered with milk, ginger, cardamom, cinnamon and cloves. Sweet, spiced, properly boiled.',
    cuisine: 'Indian',
    meal: 'drink',
    serves: 2,
    total: 15,
    active: 15,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['warm', 'spiced', 'afternoon'],
    equipment: ['small pot'],
    techniques: ['simmering'],
    ing: ['300 ml water', '1 thumb ginger, sliced', '4 cardamom pods, crushed', '1 cinnamon stick', '3 cloves', '2 tbsp black tea leaves', '300 ml milk', '2 tbsp sugar'],
    steps: [
      ['Spices', 'Simmer the water with the ginger, cardamom, cinnamon and cloves for 5 minutes.', 300, 'Medium heat'],
      ['Tea and milk', 'Add the tea and milk and bring back to a boil. Let it rise, take it off, let it fall, and repeat twice — this is what makes it taste like chai from a stall.', 240, 'Medium-high heat'],
      ['Strain', 'Stir in the sugar, strain into cups.'],
    ],
    subs: [['milk', 'oat milk', 'vegan']],
    n: [120, 4, 18, 4],
    caption: 'Chai, boiled three times like it should be.',
    daysAgo: 41,
  },
  {
    emoji: '🥭',
    title: 'Mango lassi',
    summary: 'Ripe mango, yogurt, a little cardamom and ice, blended smooth. The drink to cool a curry down.',
    cuisine: 'Indian',
    meal: 'drink',
    serves: 2,
    total: 5,
    active: 5,
    level: 'easy',
    diet: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['cold', 'blender', 'quick'],
    equipment: ['blender'],
    techniques: ['blending'],
    ing: ['1 mango, ripe, chopped', '200 g yogurt', '100 ml milk', '1 tbsp honey', 'pinch cardamom, ground', '4 ice cubes'],
    steps: [['Blend', 'Blend everything until smooth and frothy. Taste for sweetness; ripe mango may need no honey at all.']],
    subs: [['yogurt and milk', 'coconut yogurt and oat milk', 'vegan']],
    n: [190, 6, 34, 3],
    caption: 'Mango lassi. Two minutes, one blender.',
    daysAgo: 42,
  },
  {
    emoji: '✨',
    title: 'Golden turmeric latte',
    summary: 'Warm oat milk whisked with turmeric, ginger, cinnamon, black pepper and a touch of maple. A cosy, caffeine-free evening drink.',
    cuisine: 'Modern',
    meal: 'drink',
    serves: 1,
    total: 8,
    active: 8,
    level: 'easy',
    diet: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    tags: ['warm', 'evening', 'caffeine-free'],
    equipment: ['small pot'],
    techniques: ['whisking'],
    ing: ['250 ml oat milk', '1 tsp turmeric', '1/2 tsp ginger, ground', '1/2 tsp cinnamon', 'pinch black pepper', '1 tsp coconut oil', '1 tsp maple syrup'],
    steps: [
      ['Warm', 'Warm the oat milk with the turmeric, ginger, cinnamon, pepper and coconut oil, whisking, until steaming but not boiling.', 240, 'Medium-low heat', 'Black pepper is not decorative — it helps the turmeric do its thing.'],
      ['Sweeten', 'Stir in the maple syrup and pour into a mug. Froth with a whisk or hand frother if you like.'],
    ],
    n: [140, 2, 18, 7],
    caption: 'Golden milk for the end of the day.',
    daysAgo: 43,
  },
];
